import type { TestCase } from "../types";

// Category 1 — plain English customer messages (not always grammatically clean).
export const englishCases: TestCase[] = [
  {
    id: "en-001",
    category: "English messages",
    description: "simple polite add",
    message: "I want one zinger burger",
    intent: "add item",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "en-002",
    category: "English messages",
    description: "add with please",
    message: "Can I get a large pizza please",
    intent: "add item",
    expect: { cartChanges: true, cartAfter: [{ name: "Pizza Large 12 inch", qty: 1 }], totalAfter: 1200 },
  },
  {
    id: "en-003",
    category: "English messages",
    description: "add with word quantity",
    message: "give me two chicken sandwiches",
    intent: "add item qty 2",
    expect: { cartChanges: true, cartAfter: [{ name: "Chicken Sandwich", qty: 2 }], totalAfter: 1100 },
  },
  {
    id: "en-004",
    category: "English messages",
    description: "I'll have phrasing",
    message: "I'll have the chicken steak",
    intent: "add item",
    expect: { cartChanges: true, cartAfter: [{ name: "Chicken Steak", qty: 1 }], totalAfter: 950 },
  },
  {
    id: "en-005",
    category: "English messages",
    description: "pure inquiry, not an order",
    message: "do you have hot shot",
    intent: "menu inquiry",
    expect: { cartChanges: false, contains: ["Hot Shot"] },
  },
  {
    id: "en-006",
    category: "English messages",
    description: "add phrased as instruction",
    message: "add a club sandwich to my order",
    intent: "add item",
    expect: { cartChanges: true, cartAfter: [{ name: "Club Sandwich", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "en-007",
    category: "English messages",
    description: "full menu request",
    message: "what's on the menu",
    intent: "show full menu",
    expect: { cartChanges: false, contains: ["Burgers", "Pizza"] },
  },
  {
    id: "en-008",
    category: "English messages",
    description: "delivery info question",
    message: "is delivery available right now",
    intent: "delivery info",
    expect: { cartChanges: false, contains: ["Delivery"] },
  },
  {
    id: "en-009",
    category: "English messages",
    description: "remove item from existing cart",
    setup: ["1 zinger burger"],
    message: "remove the burger",
    intent: "remove item",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "en-010",
    category: "English messages",
    description: "cancel order phrased with filler words real customers use",
    setup: ["1 pizza large"],
    message: "cancel my order",
    intent: "clear cart",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "en-011",
    category: "English messages",
    description: "checkout phrased with filler words real customers use",
    setup: ["1 zinger burger"],
    message: "place my order",
    intent: "checkout",
    expect: { cartChanges: false, phaseAfter: "checkout_review", contains: ["Total"] },
  },
  {
    id: "en-012",
    category: "English messages",
    description: "bare confirm during review",
    setup: ["1 zinger burger", "place order"],
    message: "confirm",
    intent: "confirm order, move to delivery/pickup",
    expect: { cartChanges: false, phaseAfter: "checkout_type", contains: ["Delivery"] },
  },
  {
    id: "en-013",
    category: "English messages",
    description: "full order through to placement",
    setup: [
      "1 zinger burger",
      "place order",
      "confirm",
      "delivery",
      "House 12 Street 5 Gulshan Karachi",
      "Ali Raza",
    ],
    message: "yes please confirm it",
    intent: "final order placement",
    expect: { cartChanges: false, confirmed: true },
  },
  {
    id: "en-014",
    category: "English messages",
    description: "soft decline keeps cart untouched",
    setup: ["1 zinger burger"],
    message: "no I'm good for now",
    intent: "decline / pause",
    expect: { cartChanges: false, contains: ["Zinger Burger"] },
  },
  {
    id: "en-015",
    category: "English messages",
    description: "social nicety with no cart",
    message: "thank you",
    intent: "off-topic small talk",
    expect: { cartChanges: false, contains: ["Think Food"] },
  },
  {
    id: "en-016",
    category: "English messages",
    description: "two items in one natural sentence",
    message: "two zinger burgers and one pasta small",
    intent: "add multiple items",
    expect: {
      cartChanges: true,
      cartAfter: [
        { name: "Zinger Burger", qty: 2 },
        { name: "Pasta Small", qty: 1 },
      ],
      totalAfter: 1500,
    },
  },
  {
    id: "en-017",
    category: "English messages",
    description: "timing question",
    message: "what time do you close",
    intent: "timing info",
    expect: { cartChanges: false, contains: ["3 AM"] },
  },
  {
    id: "en-018",
    category: "English messages",
    description: "off-menu dietary question",
    message: "is there a vegetarian option",
    intent: "off-menu / unclear, no crash",
    expect: { cartChanges: false, contains: ["Think Food"] },
  },
  {
    id: "en-019",
    category: "English messages",
    description: "payment method question",
    message: "can I pay cash on delivery",
    intent: "off-menu / unclear, no crash",
    expect: { cartChanges: false, contains: ["Think Food"] },
  },
  {
    id: "en-020",
    category: "English messages",
    description: "address question",
    message: "where are you guys located",
    intent: "location info",
    expect: { cartChanges: false, contains: ["Nazimabad"] },
  },
];
