import type { TestCase } from "../types";

// Category 2 — Roman Urdu customer messages (the dominant real-world style for this bot).
export const romanUrduCases: TestCase[] = [
  {
    id: "ru-001",
    category: "Roman Urdu messages",
    description: "short-form add with krdo",
    message: "ek zinger burger krdo",
    intent: "add 1 zinger burger",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "ru-002",
    category: "Roman Urdu messages",
    description: "abbreviation + contraction (named with 'burger' to stay unambiguous — bare 'zinger' is a 3-item family)",
    message: "zngr burger dedo",
    intent: "add 1 zinger burger",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "ru-003",
    category: "Roman Urdu messages",
    description: "digit qty + misspelled item + size",
    message: "1 piza large",
    intent: "add 1 large pizza",
    expect: { cartChanges: true, cartAfter: [{ name: "Pizza Large 12 inch", qty: 1 }], totalAfter: 1200 },
  },
  {
    id: "ru-004",
    category: "Roman Urdu messages",
    description: "compound word + chahiye",
    message: "hotshot chahiye",
    intent: "add hot shot",
    expect: { cartChanges: true, cartAfter: [{ name: "Hot Shot 8 pcs with fries", qty: 1 }], totalAfter: 800 },
  },
  {
    id: "ru-005",
    category: "Roman Urdu messages",
    description: "spaced item + add krdo",
    message: "hot shot add krdo",
    intent: "add hot shot",
    expect: { cartChanges: true, cartAfter: [{ name: "Hot Shot 8 pcs with fries", qty: 1 }], totalAfter: 800 },
  },
  {
    id: "ru-006",
    category: "Roman Urdu messages",
    description: "no verb, but unambiguously resolves to one real item",
    message: "chikn noodles",
    intent: "add chicken chowmein",
    expect: { cartChanges: true, cartAfter: [{ name: "Chicken Chowmein", qty: 1 }], totalAfter: 650 },
  },
  {
    id: "ru-007",
    category: "Roman Urdu messages",
    description: "availability question",
    message: "chowmien hai?",
    intent: "ask availability",
    expect: { cartChanges: false, contains: ["Noodles"] },
  },
  {
    id: "ru-008",
    category: "Roman Urdu messages",
    description: "checkout trigger, real phrasing",
    setup: ["ek zinger burger krdo"],
    message: "bas yahi order h",
    intent: "checkout",
    expect: { cartChanges: false, phaseAfter: "checkout_review", contains: ["Total"] },
  },
  {
    id: "ru-009",
    category: "Roman Urdu messages",
    description: "checkout with trailing words",
    setup: ["ek zinger burger krdo"],
    message: "order place krdo mera",
    intent: "checkout",
    expect: { cartChanges: false, phaseAfter: "checkout_review", contains: ["Total"] },
  },
  {
    id: "ru-010",
    category: "Roman Urdu messages",
    description: "increment last item by one",
    setup: ["ek zinger burger krdo"],
    message: "ek aur add kro",
    intent: "increment qty",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 2 }], totalAfter: 1000 },
  },
  {
    id: "ru-011",
    category: "Roman Urdu messages",
    description: "reduce single-item cart to zero -> removed",
    setup: ["ek zinger burger krdo"],
    message: "ek hata do",
    intent: "remove 1 unit (cart had only 1)",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "ru-012",
    category: "Roman Urdu messages",
    description: "confirm during review",
    setup: ["ek zinger burger krdo", "bas yahi order h"],
    message: "confirm krdo",
    intent: "confirm, move to delivery/pickup",
    expect: { cartChanges: false, phaseAfter: "checkout_type", contains: ["Delivery"] },
  },
  {
    id: "ru-013",
    category: "Roman Urdu messages",
    description: "name extraction mid checkout",
    setup: [
      "ek zinger burger krdo",
      "bas yahi order h",
      "confirm krdo",
      "delivery krdo",
      "House 10 Street 3 Nazimabad Karachi",
    ],
    message: "mera naam fahad hai",
    intent: "provide name",
    expect: { cartChanges: false, phaseAfter: "checkout_summary", contains: ["Fahad"] },
  },
  {
    id: "ru-014",
    category: "Roman Urdu messages",
    description: "select delivery",
    setup: ["ek zinger burger krdo", "bas yahi order h", "confirm krdo"],
    message: "delivery krdo",
    intent: "select delivery type",
    expect: { cartChanges: false, phaseAfter: "checkout_address", contains: ["address"] },
  },
  {
    id: "ru-015",
    category: "Roman Urdu messages",
    description: "select pickup",
    setup: ["ek zinger burger krdo", "bas yahi order h", "confirm krdo"],
    message: "pickup chahiye",
    intent: "select pickup type",
    expect: { cartChanges: false, phaseAfter: "checkout_name", contains: ["naam"] },
  },
  {
    id: "ru-016",
    category: "Roman Urdu messages",
    description: "hypothetical-style total query, no cart change",
    setup: ["ek zinger burger krdo"],
    message: "abhi add nahi karna sirf total batao",
    intent: "ask total without adding",
    expect: { cartChanges: false, contains: ["Total"] },
  },
  {
    id: "ru-017",
    category: "Roman Urdu messages",
    description: "bas itna variant",
    setup: ["ek zinger burger krdo"],
    message: "bs itna hi",
    intent: "checkout",
    expect: { cartChanges: false, phaseAfter: "checkout_review", contains: ["Total"] },
  },
  {
    id: "ru-018",
    category: "Roman Urdu messages",
    description: "soft decline keeps cart",
    setup: ["ek zinger burger krdo"],
    message: "zaroorat nahi hai abhi",
    intent: "decline / pause",
    expect: { cartChanges: false, contains: ["Zinger Burger"] },
  },
  {
    id: "ru-019",
    category: "Roman Urdu messages",
    description: "total query unusual phrasing",
    setup: ["ek zinger burger krdo", "ek pasta small bhi de do"],
    message: "kitna hua total",
    intent: "ask total",
    expect: { cartChanges: false, contains: ["Total"] },
  },
  {
    id: "ru-020",
    category: "Roman Urdu messages",
    description: "explicit urdu numeral two + verb phrase in same message",
    message: "do zinger burger de do",
    intent: "add 2 zinger burgers",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 2 }], totalAfter: 1000 },
  },
  {
    id: "ru-021",
    category: "Roman Urdu messages",
    description: "size correction after add",
    setup: ["ek pizza regular mangwa do"],
    message: "large kar do",
    intent: "swap regular pizza for large",
    expect: { cartChanges: true, cartAfter: [{ name: "Pizza Large 12 inch", qty: 1 }], totalAfter: 1200 },
  },
  {
    id: "ru-022",
    category: "Roman Urdu messages",
    description: "category-only word, ask which one",
    message: "burger chahiye",
    intent: "ask which burger",
    expect: { cartChanges: false, contains: ["burger"] },
  },
  {
    id: "ru-023",
    category: "Roman Urdu messages",
    description: "polite multi-word add",
    message: "mujhe ek chicken steak chahiye",
    intent: "add chicken steak",
    expect: { cartChanges: true, cartAfter: [{ name: "Chicken Steak", qty: 1 }], totalAfter: 950 },
  },
  {
    id: "ru-024",
    category: "Roman Urdu messages",
    description: "price query in Roman Urdu",
    message: "zinger ka rate kya hai",
    intent: "price inquiry",
    expect: { cartChanges: false, contains: ["500"] },
  },
  {
    id: "ru-025",
    category: "Roman Urdu messages",
    description: "wants three of an item",
    message: "teen smoke burger de do",
    intent: "add 3 smoke burgers",
    expect: { cartChanges: true, cartAfter: [{ name: "Smoke Burger", qty: 3 }], totalAfter: 1650 },
  },
];
