import type { TestCase } from "../types";

// Category 3 — Hinglish (English + Roman Urdu mixed mid-sentence).
export const hinglishCases: TestCase[] = [
  {
    id: "hi-001",
    category: "Hinglish messages",
    description: "english verb + urdu item",
    message: "please add ek zinger burger",
    intent: "add 1 zinger burger",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "hi-002",
    category: "Hinglish messages",
    description: "mixed sentence, two items",
    message: "mujhe ek pizza small and ek pasta large chahiye",
    intent: "add two items",
    expect: {
      cartChanges: true,
      cartAfter: [
        { name: "Pizza Small 6 inch", qty: 1 },
        { name: "Pasta Large", qty: 1 },
      ],
      totalAfter: 1150,
    },
  },
  {
    id: "hi-003",
    category: "Hinglish messages",
    description: "english quantity word + urdu item",
    message: "give me do chicken sandwich",
    intent: "add 2 chicken sandwich",
    expect: { cartChanges: true, cartAfter: [{ name: "Chicken Sandwich", qty: 2 }], totalAfter: 1100 },
  },
  {
    id: "hi-004",
    category: "Hinglish messages",
    description: "code-switch mid sentence for checkout",
    setup: ["ek zinger burger krdo"],
    message: "ok now place order kar do",
    intent: "checkout",
    expect: { cartChanges: false, phaseAfter: "checkout_review", contains: ["Total"] },
  },
  {
    id: "hi-005",
    category: "Hinglish messages",
    description: "english remove + urdu target",
    setup: ["ek pizza large krdo"],
    message: "remove kar do pizza",
    intent: "remove pizza",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "hi-006",
    category: "Hinglish messages",
    description: "mixed total query",
    setup: ["ek zinger burger krdo"],
    message: "abhi total kitna hoga with delivery",
    intent: "ask total",
    expect: { cartChanges: false, contains: ["Total"] },
  },
  {
    id: "hi-007",
    category: "Hinglish messages",
    description: "yeh wala / this one style item naming",
    message: "ek burger and ek rice bhi de do",
    intent: "category clarification for both",
    expect: { cartChanges: false, contains: ["burger"] },
  },
  {
    id: "hi-008",
    category: "Hinglish messages",
    description: "english greeting + urdu request",
    message: "hi bhai zinger burger chahiye",
    intent: "add zinger burger",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "hi-009",
    category: "Hinglish messages",
    description: "english confirm word",
    setup: ["ek zinger burger krdo", "place order"],
    message: "yes confirm",
    intent: "confirm order",
    expect: { cartChanges: false, phaseAfter: "checkout_type", contains: ["Delivery"] },
  },
  {
    id: "hi-010",
    category: "Hinglish messages",
    description: "mixed cancel phrasing",
    setup: ["ek zinger burger krdo"],
    message: "sab cancel kar do please",
    intent: "clear cart",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "hi-011",
    category: "Hinglish messages",
    description: "switching languages for qty",
    message: "ek pizza large aur do chicken sandwich",
    intent: "add pizza + 2 sandwiches",
    expect: {
      cartChanges: true,
      cartAfter: [
        { name: "Pizza Large 12 inch", qty: 1 },
        { name: "Chicken Sandwich", qty: 2 },
      ],
      totalAfter: 2300,
    },
  },
  {
    id: "hi-012",
    category: "Hinglish messages",
    description: "informal mixed acceptance after decline",
    setup: ["ek zinger burger krdo"],
    message: "no wait actually rehne do",
    intent: "decline / pause",
    expect: { cartChanges: false, contains: ["Zinger Burger"] },
  },
  {
    id: "hi-013",
    category: "Hinglish messages",
    description: "swap item, mixed language",
    setup: ["ek zinger burger lena hai"],
    message: "zinger nahi smoke burger kar do",
    intent: "swap zinger for smoke burger",
    expect: { cartChanges: true, cartAfter: [{ name: "Smoke Burger", qty: 1 }], totalAfter: 550 },
  },
  {
    id: "hi-014",
    category: "Hinglish messages",
    description: "mixed unavailable item",
    message: "ek chai bhi de do please",
    intent: "off-menu item",
    expect: { cartChanges: false, contains: ["Drinks"] },
  },
  {
    id: "hi-015",
    category: "Hinglish messages",
    description: "mixed long-ish sentence",
    message: "bhai ek hot shot aur ek pasta small dono add kar do",
    intent: "add 2 items",
    expect: {
      cartChanges: true,
      cartAfter: [
        { name: "Hot Shot 8 pcs with fries", qty: 1 },
        { name: "Pasta Small", qty: 1 },
      ],
      totalAfter: 1300,
    },
  },
  {
    id: "hi-016",
    category: "Hinglish messages",
    description: "english 'one more' on urdu cart",
    setup: ["ek zinger burger krdo"],
    message: "one more please",
    intent: "increment last item",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 2 }], totalAfter: 1000 },
  },
  {
    id: "hi-017",
    category: "Hinglish messages",
    description: "mixed delivery selection",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo"],
    message: "delivery please karein",
    intent: "select delivery",
    expect: { cartChanges: false, phaseAfter: "checkout_address", contains: ["address"] },
  },
  {
    id: "hi-018",
    category: "Hinglish messages",
    description: "mixed pickup selection",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo"],
    message: "I'll do pickup",
    intent: "select pickup",
    expect: { cartChanges: false, phaseAfter: "checkout_name", contains: ["naam"] },
  },
  {
    id: "hi-019",
    category: "Hinglish messages",
    description: "mixed name response",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "pickup chahiye"],
    message: "my naam is Ahmed",
    intent: "provide name",
    expect: { cartChanges: false, phaseAfter: "checkout_summary", contains: ["Ahmed"] },
  },
  {
    id: "hi-020",
    category: "Hinglish messages",
    description: "mixed budget question",
    message: "1000 rs mein kya milega for 2 logon ke liye",
    intent: "budget recommendation",
    expect: { cartChanges: false, contains: ["1000"] },
  },
];
