import type { TestCase } from "../types";

// Category 4 — short-form / abbreviated messages real customers send.
export const shortFormCases: TestCase[] = [
  {
    id: "sf-001",
    category: "Short form messages",
    description: "bare abbreviation with no order signal — 'zinger' is now an item FAMILY (3 variants), so this browses the burger menu rather than guessing which one",
    message: "zngr",
    intent: "browse burger menu (consistent with other bare category-ish words)",
    expect: { cartChanges: false, contains: ["Burger"] },
  },
  {
    id: "sf-002",
    category: "Short form messages",
    description: "br for burger is too ambiguous, off menu",
    message: "1 brgr",
    intent: "normalized to burger category word, ambiguous",
    expect: { cartChanges: false, contains: ["burger"] },
  },
  {
    id: "sf-003",
    category: "Short form messages",
    description: "rmv shorthand",
    setup: ["zngr burger"],
    message: "rmv it",
    intent: "remove last item",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "sf-004",
    category: "Short form messages",
    description: "cncl shorthand",
    setup: ["zngr burger"],
    message: "cncl order",
    intent: "clear cart",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "sf-005",
    category: "Short form messages",
    description: "plz shorthand for please",
    message: "1 pasta small plz",
    intent: "add pasta small",
    expect: { cartChanges: true, cartAfter: [{ name: "Pasta Small", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "sf-006",
    category: "Short form messages",
    description: "btao shorthand",
    message: "menu btao",
    intent: "show menu",
    expect: { cartChanges: false, contains: ["Menu"] },
  },
  {
    id: "sf-007",
    category: "Short form messages",
    description: "thk shorthand acceptance",
    setup: ["zngr burger"],
    message: "thk h",
    intent: "acknowledge, keep cart",
    expect: { cartChanges: false, contains: ["Zinger Burger"] },
  },
  {
    id: "sf-008",
    category: "Short form messages",
    description: "psta shorthand",
    message: "psta large",
    intent: "add pasta large",
    expect: { cartChanges: true, cartAfter: [{ name: "Pasta Large", qty: 1 }], totalAfter: 600 },
  },
  {
    id: "sf-009",
    category: "Short form messages",
    description: "sndwch shorthand",
    message: "sndwch chahiye",
    intent: "ask which sandwich",
    expect: { cartChanges: false, contains: ["sandwich"] },
  },
  {
    id: "sf-010",
    category: "Short form messages",
    description: "single digit qty + short item (named with 'burger' to stay unambiguous)",
    message: "2 zngr burger",
    intent: "add 2 zinger burgers",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 2 }], totalAfter: 1000 },
  },
  {
    id: "sf-011",
    category: "Short form messages",
    description: "ok as standalone with active cart",
    setup: ["zngr burger"],
    message: "ok",
    intent: "acknowledge, keep cart",
    expect: { cartChanges: false, contains: ["Zinger Burger"] },
  },
  {
    id: "sf-012",
    category: "Short form messages",
    description: "yes/haan to finalize order at summary",
    setup: [
      "zngr burger",
      "place order",
      "confirm krdo",
      "delivery krdo",
      "House 1 Street 2 Karachi",
      "Sara",
    ],
    message: "ji",
    intent: "place order",
    expect: { cartChanges: false, confirmed: true },
  },
  {
    id: "sf-013",
    category: "Short form messages",
    description: "single word availability check",
    message: "fries?",
    intent: "browse pizza fries",
    expect: { cartChanges: false, contains: ["Fries"] },
  },
  {
    id: "sf-014",
    category: "Short form messages",
    description: "steak shorthand single word add",
    message: "steak",
    intent: "add chicken steak (unambiguous single-word identifier)",
    expect: { cartChanges: true, cartAfter: [{ name: "Chicken Steak", qty: 1 }], totalAfter: 950 },
  },
  {
    id: "sf-015",
    category: "Short form messages",
    description: "gyro single word",
    message: "gyro",
    intent: "add gyro",
    expect: { cartChanges: true, cartAfter: [{ name: "Gyro", qty: 1 }], totalAfter: 550 },
  },
];
