import type { TestCase } from "../types";

// Category 5 — common spelling mistakes real customers make typing fast on a phone.
export const spellingMistakeCases: TestCase[] = [
  {
    id: "sp-001",
    category: "Spelling mistakes",
    description: "piza misspelling",
    message: "ek piza small chahiye",
    intent: "add small pizza",
    expect: { cartChanges: true, cartAfter: [{ name: "Pizza Small 6 inch", qty: 1 }], totalAfter: 550 },
  },
  {
    id: "sp-002",
    category: "Spelling mistakes",
    description: "chikn misspelling",
    message: "ek chikn steak chahiye",
    intent: "add chicken steak",
    expect: { cartChanges: true, cartAfter: [{ name: "Chicken Steak", qty: 1 }], totalAfter: 950 },
  },
  {
    id: "sp-003",
    category: "Spelling mistakes",
    description: "chowmien misspelling",
    message: "ek chicken chowmien chahiye",
    intent: "add chicken chowmein",
    expect: { cartChanges: true, cartAfter: [{ name: "Chicken Chowmein", qty: 1 }], totalAfter: 650 },
  },
  {
    id: "sp-004",
    category: "Spelling mistakes",
    description: "noodels misspelling",
    message: "vegetable noodels chahiye",
    intent: "add vegetable chowmein",
    expect: { cartChanges: true, cartAfter: [{ name: "Vegetable Chowmein", qty: 1 }], totalAfter: 600 },
  },
  {
    id: "sp-005",
    category: "Spelling mistakes",
    description: "sandwitch misspelling",
    message: "ek club sandwitch chahiye",
    intent: "add club sandwich",
    expect: { cartChanges: true, cartAfter: [{ name: "Club Sandwich", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "sp-006",
    category: "Spelling mistakes",
    description: "double letter typo on burger",
    message: "ek zinger brger chahiye",
    intent: "add zinger burger",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "sp-007",
    category: "Spelling mistakes",
    description: "nhi / nahi typo handling in remove",
    setup: ["ek zinger burger krdo"],
    message: "ye nhi chahiye",
    intent: "remove last item",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "sp-008",
    category: "Spelling mistakes",
    description: "krna typo",
    message: "order krna hai ek smoke burger",
    intent: "add smoke burger",
    expect: { cartChanges: true, cartAfter: [{ name: "Smoke Burger", qty: 1 }], totalAfter: 550 },
  },
  {
    id: "sp-009",
    category: "Spelling mistakes",
    description: "mjy typo for mujhe",
    message: "mjy ek gyro chahiye",
    intent: "add gyro",
    expect: { cartChanges: true, cartAfter: [{ name: "Gyro", qty: 1 }], totalAfter: 550 },
  },
  {
    id: "sp-010",
    category: "Spelling mistakes",
    description: "psta misspelling with sauce variant",
    message: "ek alfredopasta chahiye",
    intent: "add alfredo pasta",
    expect: { cartChanges: true, cartAfter: [{ name: "Alfredo Pasta white sauce", qty: 1 }], totalAfter: 850 },
  },
  {
    id: "sp-011",
    category: "Spelling mistakes",
    description: "multiple typos in one message",
    message: "ek chikn sndwch aur ek piza small chahiye",
    intent: "add chicken sandwich + small pizza",
    expect: {
      cartChanges: true,
      cartAfter: [
        { name: "Chicken Sandwich", qty: 1 },
        { name: "Pizza Small 6 inch", qty: 1 },
      ],
      totalAfter: 1100,
    },
  },
  {
    id: "sp-012",
    category: "Spelling mistakes",
    description: "thik / thk typo accepted as ack",
    setup: ["ek zinger burger krdo"],
    message: "thik hai",
    intent: "acknowledge, keep cart",
    expect: { cartChanges: false, contains: ["Zinger Burger"] },
  },
  {
    id: "sp-013",
    category: "Spelling mistakes",
    description: "kitny typo for kitna",
    message: "smoke burger kitny ka hai",
    intent: "price inquiry",
    expect: { cartChanges: false, contains: ["550"] },
  },
  {
    id: "sp-014",
    category: "Spelling mistakes",
    description: "dikhado typo",
    message: "rice ka menu dikhado",
    intent: "browse rice menu",
    expect: { cartChanges: false, contains: ["Rice"] },
  },
  {
    id: "sp-015",
    category: "Spelling mistakes",
    description: "han typo for haan with active cart",
    setup: ["ek zinger burger krdo"],
    message: "han thik hai",
    intent: "acknowledge, keep cart",
    expect: { cartChanges: false, contains: ["Zinger Burger"] },
  },
];
