import type { TestCase } from "../types";

// Category 6 — messages where real customers ran words together with no spaces.
export const missingSpacesCases: TestCase[] = [
  {
    id: "ms-001",
    category: "Missing spaces",
    description: "compound burger name with no space",
    message: "ek zingerburger chahiye",
    intent: "add zinger burger",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "ms-002",
    category: "Missing spaces",
    description: "compound sandwich name with no space",
    message: "ek chickensandwich chahiye",
    intent: "add chicken sandwich",
    expect: { cartChanges: true, cartAfter: [{ name: "Chicken Sandwich", qty: 1 }], totalAfter: 550 },
  },
  {
    id: "ms-003",
    category: "Missing spaces",
    description: "compound steak name with no space",
    message: "ek chickensteak chahiye",
    intent: "add chicken steak",
    expect: { cartChanges: true, cartAfter: [{ name: "Chicken Steak", qty: 1 }], totalAfter: 950 },
  },
  {
    id: "ms-004",
    category: "Missing spaces",
    description: "compound rice name with no space",
    message: "ek chickenfriedrice chahiye",
    intent: "add chicken fried rice",
    expect: { cartChanges: true, cartAfter: [{ name: "Chicken Fried Rice", qty: 1 }], totalAfter: 450 },
  },
  {
    id: "ms-005",
    category: "Missing spaces",
    description: "hotshot run together",
    message: "ek hotshot chahiye",
    intent: "add hot shot",
    expect: { cartChanges: true, cartAfter: [{ name: "Hot Shot 8 pcs with fries", qty: 1 }], totalAfter: 800 },
  },
  {
    id: "ms-006",
    category: "Missing spaces",
    description: "pizzafries run together",
    message: "ek pizzafries chahiye",
    intent: "ask which pizza fries size",
    expect: { cartChanges: false, contains: ["Fries"] },
  },
  {
    id: "ms-007",
    category: "Missing spaces",
    description: "smokeburger run together",
    message: "ek smokeburger chahiye",
    intent: "add smoke burger",
    expect: { cartChanges: true, cartAfter: [{ name: "Smoke Burger", qty: 1 }], totalAfter: 550 },
  },
  {
    id: "ms-008",
    category: "Missing spaces",
    description: "wholemessage no spaces at all",
    message: "ekzingerburgerchahiye",
    intent: "unparseable run-on text, no crash",
    expect: { cartChanges: false },
  },
  {
    id: "ms-009",
    category: "Missing spaces",
    description: "mexicanpizza run together",
    message: "ek mexicanpizza chahiye",
    intent: "add mexican pizza",
    expect: { cartChanges: true, cartAfter: [{ name: "Mexican Pizza", qty: 1 }], totalAfter: 1600 },
  },
  {
    id: "ms-010",
    category: "Missing spaces",
    description: "singaporeanrice run together",
    message: "ek singaporeanrice chahiye",
    intent: "add singaporean rice",
    expect: { cartChanges: true, cartAfter: [{ name: "Singaporean Rice", qty: 1 }], totalAfter: 700 },
  },
  {
    id: "ms-011",
    category: "Missing spaces",
    description: "grillsandwich run together",
    message: "ek grillsandwich chahiye",
    intent: "add grill sandwich",
    expect: { cartChanges: true, cartAfter: [{ name: "Grill Sandwich", qty: 1 }], totalAfter: 650 },
  },
  {
    id: "ms-012",
    category: "Missing spaces",
    description: "clubsandwich run together",
    message: "ek clubsandwich chahiye",
    intent: "add club sandwich",
    expect: { cartChanges: true, cartAfter: [{ name: "Club Sandwich", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "ms-013",
    category: "Missing spaces",
    description: "pizzalarge run together",
    message: "ek pizzalarge chahiye",
    intent: "add pizza large",
    expect: { cartChanges: true, cartAfter: [{ name: "Pizza Large 12 inch", qty: 1 }], totalAfter: 1200 },
  },
  {
    id: "ms-014",
    category: "Missing spaces",
    description: "pizzasmall run together",
    message: "ek pizzasmall chahiye",
    intent: "add pizza small",
    expect: { cartChanges: true, cartAfter: [{ name: "Pizza Small 6 inch", qty: 1 }], totalAfter: 550 },
  },
  {
    id: "ms-015",
    category: "Missing spaces",
    description: "jumbozinger run together",
    message: "ek jumbozinger chahiye",
    intent: "add jumbo zinger",
    expect: { cartChanges: true, cartAfter: [{ name: "Jumbo Zinger", qty: 1 }], totalAfter: 750 },
  },
];
