import type { TestCase } from "../types";

// Category 7 — messages with irregular / extra whitespace, real keyboard-typing artifacts.
export const extraSpacesCases: TestCase[] = [
  {
    id: "es-001",
    category: "Extra spaces",
    description: "extra spaces between every word",
    message: "ek   zinger    burger   chahiye",
    intent: "add zinger burger",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "es-002",
    category: "Extra spaces",
    description: "leading and trailing whitespace",
    message: "   1 pasta small   ",
    intent: "add pasta small",
    expect: { cartChanges: true, cartAfter: [{ name: "Pasta Small", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "es-003",
    category: "Extra spaces",
    description: "tabs / multiple spaces mixed with size",
    message: "pizza     large     2",
    intent: "add 2 large pizzas",
    expect: { cartChanges: true, cartAfter: [{ name: "Pizza Large 12 inch", qty: 2 }], totalAfter: 2400 },
  },
  {
    id: "es-004",
    category: "Extra spaces",
    description: "extra spaces around comma-separated items",
    message: "ek zinger burger  ,   ek pasta small  chahiye",
    intent: "add zinger burger + pasta small",
    expect: {
      cartChanges: true,
      cartAfter: [
        { name: "Zinger Burger", qty: 1 },
        { name: "Pasta Small", qty: 1 },
      ],
      totalAfter: 1000,
    },
  },
  {
    id: "es-005",
    category: "Extra spaces",
    description: "double spaces in remove command",
    setup: ["ek zinger burger krdo"],
    message: "zinger   hata    do",
    intent: "remove zinger burger",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "es-006",
    category: "Extra spaces",
    description: "spaces inside checkout phrase",
    setup: ["ek zinger burger krdo"],
    message: "bas   yahi   order   h",
    intent: "checkout",
    expect: { cartChanges: false, phaseAfter: "checkout_review", contains: ["Total"] },
  },
  {
    id: "es-007",
    category: "Extra spaces",
    description: "newline-like multiple spaces around confirm",
    setup: ["ek zinger burger krdo", "place order"],
    message: "   confirm   ",
    intent: "confirm order",
    expect: { cartChanges: false, phaseAfter: "checkout_type", contains: ["Delivery"] },
  },
  {
    id: "es-008",
    category: "Extra spaces",
    description: "extra spaces with PKR copy paste",
    message: "Zinger Burger    —    PKR 500   add kro",
    intent: "add zinger burger from copied line",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "es-009",
    category: "Extra spaces",
    description: "spaces around aur separator",
    message: "ek smoke burger   aur   ek hot shot",
    intent: "add smoke burger + hot shot",
    expect: {
      cartChanges: true,
      cartAfter: [
        { name: "Smoke Burger", qty: 1 },
        { name: "Hot Shot 8 pcs with fries", qty: 1 },
      ],
      totalAfter: 1350,
    },
  },
  {
    id: "es-010",
    category: "Extra spaces",
    description: "only whitespace message, no crash",
    message: "      ",
    intent: "empty/whitespace input",
    expect: { cartChanges: false },
  },
  {
    id: "es-011",
    category: "Extra spaces",
    description: "extra spaces inside item name",
    message: "ek  smoke  sandwich  chahiye",
    intent: "add smoke sandwich",
    expect: { cartChanges: true, cartAfter: [{ name: "Smoke Sandwich", qty: 1 }], totalAfter: 550 },
  },
  {
    id: "es-012",
    category: "Extra spaces",
    description: "extra spaces in remove command",
    setup: ["ek zinger burger krdo"],
    message: "remove  kar  do  zinger",
    intent: "remove zinger burger",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "es-013",
    category: "Extra spaces",
    description: "extra spaces around every word in a two-item message",
    message: "ek   gyro   aur   ek   wrap   chahiye",
    intent: "add gyro + wrap",
    expect: {
      cartChanges: true,
      cartAfter: [
        { name: "Gyro", qty: 1 },
        { name: "Wrap", qty: 1 },
      ],
      totalAfter: 1100,
    },
  },
  {
    id: "es-014",
    category: "Extra spaces",
    description: "leading/trailing spaces around cancel command",
    setup: ["ek zinger burger krdo"],
    message: "  cancel   order  ",
    intent: "clear cart",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "es-015",
    category: "Extra spaces",
    description: "multiple spaces between digit qty and item",
    message: "1    pizza    large",
    intent: "add pizza large",
    expect: { cartChanges: true, cartAfter: [{ name: "Pizza Large 12 inch", qty: 1 }], totalAfter: 1200 },
  },
];
