import type { TestCase } from "../types";

// Category 9 — multiple distinct actions packed into a single customer message.
export const multipleActionsCases: TestCase[] = [
  {
    id: "ma-001",
    category: "Multiple actions in one message",
    description: "remove one item and add another in one go",
    setup: ["ek zinger burger krdo"],
    message: "ek small fries add kardo or burger hatado",
    intent: "remove zinger burger, add pizza fries small",
    expect: {
      cartChanges: true,
      cartAfter: [{ name: "Pizza Fries Small Box", qty: 1 }],
      totalAfter: 500,
    },
  },
  {
    id: "ma-002",
    category: "Multiple actions in one message",
    description: "increase qty of one item, add a different one",
    setup: ["ek zinger burger krdo"],
    message: "ek aur zinger aur ek pasta small bhi de do",
    intent: "add another zinger + add pasta small",
    expect: { cartChanges: true },
  },
  {
    id: "ma-003",
    category: "Multiple actions in one message",
    description: "ask for total then immediately add",
    setup: ["ek zinger burger krdo"],
    message: "total kitna hai aur ek pasta small bhi add kr do",
    intent: "add pasta small while asking total",
    expect: { cartChanges: true, contains: ["Total"] },
  },
  {
    id: "ma-004",
    category: "Multiple actions in one message",
    description: "remove two different items in one message",
    setup: ["ek zinger burger krdo", "ek pasta small bhi de do"],
    message: "zinger hata do aur pasta bhi hata do",
    intent: "remove both items",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "ma-005",
    category: "Multiple actions in one message",
    description: "checkout intent combined with a new item add",
    setup: ["ek zinger burger krdo"],
    message: "ek pasta small bhi add kr do aur order place kr do",
    intent: "add pasta small then move to checkout review",
    expect: { cartChanges: true, phaseAfter: "checkout_review" },
  },
  {
    id: "ma-006",
    category: "Multiple actions in one message",
    description: "cancel everything and add a brand new item",
    setup: ["ek zinger burger krdo", "ek pasta small bhi de do"],
    message: "remove everything and add 1 large pizza",
    intent: "clear cart then add large pizza",
    expect: { cartChanges: true, cartAfter: [{ name: "Pizza Large 12 inch", qty: 1 }], totalAfter: 1200 },
  },
  {
    id: "ma-007",
    category: "Multiple actions in one message",
    description: "clear everything in roman urdu, add grill sandwich",
    setup: ["ek zinger burger krdo"],
    message: "sab hata do aur ek grill sandwich add kro",
    intent: "clear cart then add grill sandwich",
    expect: { cartChanges: true, cartAfter: [{ name: "Grill Sandwich", qty: 1 }], totalAfter: 650 },
  },
  {
    id: "ma-008",
    category: "Multiple actions in one message",
    description: "remove an item that is not even in the cart, named explicitly",
    setup: ["ek zinger burger krdo"],
    message: "sandwich remove kro when sandwich is not in cart",
    intent: "no-op remove, item not present",
    expect: { cartChanges: false, contains: ["Zinger Burger"] },
  },
  {
    id: "ma-009",
    category: "Multiple actions in one message",
    description: "add two different items and remove one of them in the same message",
    setup: ["ek zinger burger krdo"],
    message: "ek pizza small add kro aur zinger hata do",
    intent: "add pizza small, remove zinger",
    expect: { cartChanges: true, cartAfter: [{ name: "Pizza Small 6 inch", qty: 1 }], totalAfter: 550 },
  },
  {
    id: "ma-010",
    category: "Multiple actions in one message",
    description: "increase quantity and ask about delivery in one message",
    setup: ["ek zinger burger krdo"],
    message: "ek aur zinger add kr do aur delivery kitne time mein hogi",
    intent: "increment zinger qty, also answers delivery time",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 2 }], totalAfter: 1000 },
  },
  {
    id: "ma-011",
    category: "Multiple actions in one message",
    description: "add two items separated by digit qty and 'sath' connector",
    message: "2 zinger burger add kr do aur sath mein ek pasta small bhi",
    intent: "add 2 zinger burgers + 1 pasta small",
    expect: {
      cartChanges: true,
      cartAfter: [
        { name: "Zinger Burger", qty: 2 },
        { name: "Pasta Small", qty: 1 },
      ],
      totalAfter: 1500,
    },
  },
  {
    id: "ma-012",
    category: "Multiple actions in one message",
    description: "english remove + add with digit qty in same message",
    setup: ["ek pizza large bhi de do"],
    message: "remove the pizza and add 2 zinger burgers",
    intent: "remove pizza, add 2 zinger burgers",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 2 }], totalAfter: 1000 },
  },
  {
    id: "ma-013",
    category: "Multiple actions in one message",
    description: "add item then checkout in same message",
    message: "ek hot shot add kr do, checkout kr do",
    intent: "add hot shot then move to checkout review",
    expect: { cartChanges: true, cartAfter: [{ name: "Hot Shot 8 pcs with fries", qty: 1 }], phaseAfter: "checkout_review" },
  },
  {
    id: "ma-014",
    category: "Multiple actions in one message",
    description: "add item then checkout, with existing cart item untouched",
    setup: ["ek pasta small bhi de do"],
    message: "ek pizza small add karo, checkout kr do",
    intent: "add pizza small, keep pasta small, move to checkout review",
    expect: {
      cartChanges: true,
      cartAfter: [
        { name: "Pasta Small", qty: 1 },
        { name: "Pizza Small 6 inch", qty: 1 },
      ],
      totalAfter: 1050,
      phaseAfter: "checkout_review",
    },
  },
  {
    id: "ma-015",
    category: "Multiple actions in one message",
    description: "add item and ask to see the order in the same message",
    message: "ek chicken steak add karo aur mera order dikhao",
    intent: "add chicken steak, response naturally shows the cart",
    expect: { cartChanges: true, cartAfter: [{ name: "Chicken Steak", qty: 1 }], totalAfter: 950 },
  },
];
