import type { TestCase } from "../types";

// Category 10 — remove AND add in the same message (distinct from pure replace).
export const removeAddSameMessageCases: TestCase[] = [
  {
    id: "ra-001",
    category: "Remove and add in same message",
    description: "remove burger, add fries",
    setup: ["ek zinger burger krdo"],
    message: "burger hata do aur fries small add kar do",
    intent: "remove zinger, add pizza fries small",
    expect: { cartChanges: true, cartAfter: [{ name: "Pizza Fries Small Box", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "ra-002",
    category: "Remove and add in same message",
    description: "remove pasta, add rice",
    setup: ["ek pasta small bhi de do"],
    message: "pasta hata do aur ek chicken fried rice de do",
    intent: "remove pasta, add chicken fried rice",
    expect: { cartChanges: true, cartAfter: [{ name: "Chicken Fried Rice", qty: 1 }], totalAfter: 450 },
  },
  {
    id: "ra-003",
    category: "Remove and add in same message",
    description: "remove everything, add a fresh item (clear + add)",
    setup: ["ek zinger burger krdo", "ek pasta small bhi de do"],
    message: "sab remove kar do aur ek mexican pizza add kar do",
    intent: "clear cart then add mexican pizza",
    expect: { cartChanges: true, cartAfter: [{ name: "Mexican Pizza", qty: 1 }], totalAfter: 1600 },
  },
  {
    id: "ra-004",
    category: "Remove and add in same message",
    description: "remove an item not present, add a valid one",
    setup: ["ek zinger burger krdo"],
    message: "pizza hata do aur ek hot shot add kar do",
    intent: "pizza not in cart (no-op), add hot shot",
    expect: { cartChanges: true, contains: ["Hot Shot"] },
  },
  {
    id: "ra-005",
    category: "Remove and add in same message",
    description: "add before remove, order reversed in sentence",
    setup: ["ek zinger burger krdo"],
    message: "ek smoke burger add kar do aur zinger hata do",
    intent: "add smoke burger, remove zinger",
    expect: { cartChanges: true, cartAfter: [{ name: "Smoke Burger", qty: 1 }], totalAfter: 550 },
  },
  {
    id: "ra-006",
    category: "Remove and add in same message",
    description: "remove sandwich, add two different items",
    setup: ["ek club sandwich chahiye"],
    message: "sandwich hata do aur ek wrap aur ek gyro add kar do",
    intent: "remove sandwich, add wrap and gyro",
    expect: { cartChanges: true },
  },
  {
    id: "ra-007",
    category: "Remove and add in same message",
    description: "explicit double-item remove and add in roman urdu",
    setup: ["ek zinger burger krdo", "ek pasta small bhi de do"],
    message: "zinger aur pasta hata do, ek alfredo pasta add kar do",
    intent: "remove zinger/pasta, add alfredo pasta",
    expect: { cartChanges: true },
  },
  {
    id: "ra-008",
    category: "Remove and add in same message",
    description: "remove burger, add pizza fries small",
    setup: ["ek zinger burger krdo"],
    message: "ek small fries add kardo or burger hatado",
    intent: "remove zinger, add pizza fries small",
    expect: { cartChanges: true, cartAfter: [{ name: "Pizza Fries Small Box", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "ra-009",
    category: "Remove and add in same message",
    description: "remove wrap, add gyro",
    setup: ["ek wrap chahiye"],
    message: "wrap hata do aur ek gyro de do",
    intent: "remove wrap, add gyro",
    expect: { cartChanges: true, cartAfter: [{ name: "Gyro", qty: 1 }], totalAfter: 550 },
  },
  {
    id: "ra-010",
    category: "Remove and add in same message",
    description: "remove smoke burger, add spicy stuff burger",
    setup: ["ek smoke burger chahiye"],
    message: "smoke burger hata do aur ek spicy stuff burger add kro",
    intent: "remove smoke burger, add spicy stuff burger",
    expect: { cartChanges: true, cartAfter: [{ name: "Spicy Stuff Burger", qty: 1 }], totalAfter: 700 },
  },
  {
    id: "ra-011",
    category: "Remove and add in same message",
    description: "remove rice category item, add egg rice",
    setup: ["ek chicken fried rice chahiye"],
    message: "rice hata do aur ek egg rice de do",
    intent: "remove fried rice, add egg rice",
    expect: { cartChanges: true, cartAfter: [{ name: "Egg Rice", qty: 1 }], totalAfter: 450 },
  },
  {
    id: "ra-012",
    category: "Remove and add in same message",
    description: "cross-replace sandwich via hata kar connector",
    setup: ["ek grill sandwich chahiye"],
    message: "sandwich hata kar club sandwich de do",
    intent: "replace grill sandwich with club sandwich",
    expect: { cartChanges: true, cartAfter: [{ name: "Club Sandwich", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "ra-013",
    category: "Remove and add in same message",
    description: "remove noodles category item, add rice",
    setup: ["ek chicken chowmein chahiye"],
    message: "noodles remove kr do aur ek singaporean rice add kr do",
    intent: "remove chowmein, add singaporean rice",
    expect: { cartChanges: true, cartAfter: [{ name: "Singaporean Rice", qty: 1 }], totalAfter: 700 },
  },
  {
    id: "ra-014",
    category: "Remove and add in same message",
    description: "remove starter category item, add hot shot",
    setup: ["ek chicken strips chahiye"],
    message: "starter hata do aur ek hot shot add kr do",
    intent: "remove chicken strips, add hot shot",
    expect: { cartChanges: true, cartAfter: [{ name: "Hot Shot 8 pcs with fries", qty: 1 }], totalAfter: 800 },
  },
  {
    id: "ra-015",
    category: "Remove and add in same message",
    description: "remove roll category item, add wrap",
    setup: ["ek gyro chahiye"],
    message: "roll hata do aur ek wrap add kr do",
    intent: "remove gyro, add wrap",
    expect: { cartChanges: true, cartAfter: [{ name: "Wrap", qty: 1 }], totalAfter: 550 },
  },
];
