import type { TestCase } from "../types";

// Category 11 — replacing one item for another (not remove+add of unrelated items).
export const replaceItemCases: TestCase[] = [
  {
    id: "rp-001",
    category: "Replace item",
    description: "swap burger variant within same category",
    setup: ["ek zinger burger lena hai"],
    message: "zinger nahi smoke burger kar do",
    intent: "swap zinger for smoke burger",
    expect: { cartChanges: true, cartAfter: [{ name: "Smoke Burger", qty: 1 }], totalAfter: 550 },
  },
  {
    id: "rp-002",
    category: "Replace item",
    description: "size correction, regular to large",
    setup: ["ek pizza regular mangwa do"],
    message: "large kar do",
    intent: "swap regular pizza for large",
    expect: { cartChanges: true, cartAfter: [{ name: "Pizza Large 12 inch", qty: 1 }], totalAfter: 1200 },
  },
  {
    id: "rp-003",
    category: "Replace item",
    description: "swap pasta sauce variant",
    setup: ["ek macaroni pasta de do"],
    message: "red sauce nahi white sauce kar do",
    intent: "swap macaroni red sauce for white sauce pasta",
    expect: { cartChanges: true },
  },
  {
    id: "rp-004",
    category: "Replace item",
    description: "explicit ki jagah replacement phrase",
    setup: ["ek zinger burger krdo"],
    message: "zinger ki jagah jumbo zinger de do",
    intent: "replace zinger with jumbo zinger",
    expect: { cartChanges: true, cartAfter: [{ name: "Jumbo Zinger", qty: 1 }], totalAfter: 750 },
  },
  {
    id: "rp-005",
    category: "Replace item",
    description: "cross-category replace via hata kar connector",
    setup: ["ek zinger burger krdo"],
    message: "zinger hata kar smoke sandwich de do",
    intent: "replace zinger burger with smoke sandwich",
    expect: { cartChanges: true, cartAfter: [{ name: "Smoke Sandwich", qty: 1 }], totalAfter: 550 },
  },
  {
    id: "rp-006",
    category: "Replace item",
    description: "replace with item not on menu — should reject gracefully",
    setup: ["ek zinger burger krdo"],
    message: "zinger hata kar daal de do",
    intent: "reject replacement, target item not on menu",
    expect: { cartChanges: false, cartAfter: [{ name: "Zinger Burger", qty: 1 }], contains: ["available nahi"] },
  },
  {
    id: "rp-007",
    category: "Replace item",
    description: "replace item that isn't even in the cart",
    setup: ["ek zinger burger krdo"],
    message: "pizza hata kar pasta de do",
    intent: "reject replacement, source item not in cart",
    expect: { cartChanges: false, cartAfter: [{ name: "Zinger Burger", qty: 1 }] },
  },
  {
    id: "rp-008",
    category: "Replace item",
    description: "replace noodles variant",
    setup: ["ek chicken chowmein chahiye"],
    message: "chicken chowmein nahi vegetable chowmein kar do",
    intent: "swap chicken chowmein for vegetable chowmein",
    expect: { cartChanges: true, cartAfter: [{ name: "Vegetable Chowmein", qty: 1 }], totalAfter: 600 },
  },
  {
    id: "rp-009",
    category: "Replace item",
    description: "category-anchored replacement, single item cart",
    setup: ["ek hot shot chahiye"],
    message: "chicken strips kar do",
    intent: "swap hot shot for chicken strips within starters",
    expect: { cartChanges: true, cartAfter: [{ name: "Chicken Strips 6 pcs with fries", qty: 1 }], totalAfter: 750 },
  },
  {
    id: "rp-010",
    category: "Replace item",
    description: "replace rice variant",
    setup: ["ek chicken fried rice chahiye"],
    message: "singaporean rice kar do",
    intent: "swap fried rice for singaporean rice",
    expect: { cartChanges: true, cartAfter: [{ name: "Singaporean Rice", qty: 1 }], totalAfter: 700 },
  },
];
