import type { TestCase } from "../types";

// Category 12 — customer signals they're ready to check out.
export const checkoutIntentCases: TestCase[] = [
  {
    id: "co-001",
    category: "Checkout intent",
    description: "classic bas yahi order phrasing",
    setup: ["ek zinger burger krdo"],
    message: "bas yahi order h",
    intent: "checkout",
    expect: { cartChanges: false, phaseAfter: "checkout_review", contains: ["Total"] },
  },
  {
    id: "co-002",
    category: "Checkout intent",
    description: "english checkout word",
    setup: ["ek zinger burger krdo"],
    message: "checkout",
    intent: "checkout",
    expect: { cartChanges: false, phaseAfter: "checkout_review", contains: ["Total"] },
  },
  {
    id: "co-003",
    category: "Checkout intent",
    description: "place order literal",
    setup: ["ek zinger burger krdo"],
    message: "place order",
    intent: "checkout",
    expect: { cartChanges: false, phaseAfter: "checkout_review", contains: ["Total"] },
  },
  {
    id: "co-004",
    category: "Checkout intent",
    description: "checkout attempted with an empty cart",
    message: "place order",
    intent: "reject — nothing to checkout",
    expect: { cartChanges: false, phaseAfter: "browsing", contains: ["select"] },
  },
  {
    id: "co-005",
    category: "Checkout intent",
    description: "checkout combined with a final item add",
    setup: ["ek zinger burger krdo"],
    message: "ek pasta small bhi de do aur order place kr do",
    intent: "add then checkout",
    expect: { cartChanges: true, phaseAfter: "checkout_review" },
  },
  {
    id: "co-006",
    category: "Checkout intent",
    description: "proceed keyword",
    setup: ["ek zinger burger krdo"],
    message: "proceed",
    intent: "checkout",
    expect: { cartChanges: false, phaseAfter: "checkout_review", contains: ["Total"] },
  },
  {
    id: "co-007",
    category: "Checkout intent",
    description: "aage chalo phrasing",
    setup: ["ek zinger burger krdo"],
    message: "aage chalo",
    intent: "checkout",
    expect: { cartChanges: false, phaseAfter: "checkout_review", contains: ["Total"] },
  },
  {
    id: "co-008",
    category: "Checkout intent",
    description: "final kar do phrasing",
    setup: ["ek zinger burger krdo"],
    message: "order final kar do",
    intent: "checkout",
    expect: { cartChanges: false, phaseAfter: "checkout_review", contains: ["Total"] },
  },
  {
    id: "co-009",
    category: "Checkout intent",
    description: "submit order phrasing",
    setup: ["ek zinger burger krdo"],
    message: "submit order",
    intent: "checkout",
    expect: { cartChanges: false, phaseAfter: "checkout_review", contains: ["Total"] },
  },
  {
    id: "co-010",
    category: "Checkout intent",
    description: "delivery type selection after review",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo"],
    message: "delivery",
    intent: "select delivery type",
    expect: { cartChanges: false, phaseAfter: "checkout_address", contains: ["address"] },
  },
  {
    id: "co-011",
    category: "Checkout intent",
    description: "pickup type selection after review",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo"],
    message: "pickup",
    intent: "select pickup type",
    expect: { cartChanges: false, phaseAfter: "checkout_name", contains: ["naam"] },
  },
  {
    id: "co-012",
    category: "Checkout intent",
    description: "rejects junk address",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "delivery"],
    message: "asdf",
    intent: "invalid address rejected",
    expect: { cartChanges: false, phaseAfter: "checkout_address", contains: ["valid"] },
  },
  {
    id: "co-013",
    category: "Checkout intent",
    description: "valid address accepted",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "delivery"],
    message: "House 45 Street 12 Nazimabad Karachi",
    intent: "address accepted",
    expect: { cartChanges: false, phaseAfter: "checkout_name", contains: ["naam"] },
  },
  {
    id: "co-014",
    category: "Checkout intent",
    description: "ready to checkout phrasing",
    setup: ["ek zinger burger krdo"],
    message: "ready to checkout",
    intent: "checkout",
    expect: { cartChanges: false, phaseAfter: "checkout_review", contains: ["Total"] },
  },
  {
    id: "co-015",
    category: "Checkout intent",
    description: "complete order phrasing",
    setup: ["ek zinger burger krdo"],
    message: "complete order",
    intent: "checkout",
    expect: { cartChanges: false, phaseAfter: "checkout_review", contains: ["Total"] },
  },
  {
    id: "co-016",
    category: "Checkout intent",
    description: "order send phrasing",
    setup: ["ek zinger burger krdo"],
    message: "order send kr do",
    intent: "checkout",
    expect: { cartChanges: false, phaseAfter: "checkout_review", contains: ["Total"] },
  },
  {
    id: "co-017",
    category: "Checkout intent",
    description: "isi ko place phrasing",
    setup: ["ek zinger burger krdo"],
    message: "isi ko place kr do",
    intent: "checkout",
    expect: { cartChanges: false, phaseAfter: "checkout_review", contains: ["Total"] },
  },
  {
    id: "co-018",
    category: "Checkout intent",
    description: "continue keyword",
    setup: ["ek zinger burger krdo"],
    message: "continue",
    intent: "checkout",
    expect: { cartChanges: false, phaseAfter: "checkout_review", contains: ["Total"] },
  },
];
