import type { TestCase } from "../types";

// Category 13 — confirming the order through to final placement.
export const confirmOrderCases: TestCase[] = [
  {
    id: "cf-001",
    category: "Confirm order",
    description: "bare confirm during review",
    setup: ["ek zinger burger krdo", "bas yahi order h"],
    message: "confirm",
    intent: "move to delivery/pickup selection",
    expect: { cartChanges: false, phaseAfter: "checkout_type", contains: ["Delivery"] },
  },
  {
    id: "cf-002",
    category: "Confirm order",
    description: "confirm order phrase",
    setup: ["ek zinger burger krdo", "bas yahi order h"],
    message: "confirm order",
    intent: "move to delivery/pickup selection",
    expect: { cartChanges: false, phaseAfter: "checkout_type", contains: ["Delivery"] },
  },
  {
    id: "cf-003",
    category: "Confirm order",
    description: "sab theek hai phrasing",
    setup: ["ek zinger burger krdo", "bas yahi order h"],
    message: "sab theek hai",
    intent: "move to delivery/pickup selection",
    expect: { cartChanges: false, phaseAfter: "checkout_type", contains: ["Delivery"] },
  },
  {
    id: "cf-004",
    category: "Confirm order",
    description: "final YES at summary places the order",
    setup: [
      "ek zinger burger krdo",
      "bas yahi order h",
      "confirm krdo",
      "delivery krdo",
      "House 5 Street 9 DHA Karachi",
      "Bilal",
    ],
    message: "YES",
    intent: "place order",
    expect: { cartChanges: false, confirmed: true },
  },
  {
    id: "cf-005",
    category: "Confirm order",
    description: "lowercase yes also places the order",
    setup: [
      "ek zinger burger krdo",
      "bas yahi order h",
      "confirm krdo",
      "pickup chahiye",
      "Ahmed Khan",
    ],
    message: "yes",
    intent: "place order",
    expect: { cartChanges: false, confirmed: true },
  },
  {
    id: "cf-006",
    category: "Confirm order",
    description: "haan at summary places the order",
    setup: [
      "ek zinger burger krdo",
      "bas yahi order h",
      "confirm krdo",
      "pickup chahiye",
      "Sana",
    ],
    message: "haan",
    intent: "place order",
    expect: { cartChanges: false, confirmed: true },
  },
  {
    id: "cf-007",
    category: "Confirm order",
    description: "cancel at the summary step aborts and clears cart",
    setup: [
      "ek zinger burger krdo",
      "bas yahi order h",
      "confirm krdo",
      "pickup chahiye",
      "Hina",
    ],
    message: "cancel",
    intent: "abort order, clear cart",
    expect: { cartChanges: true, cartAfter: [], phaseAfter: "browsing" },
  },
  {
    id: "cf-008",
    category: "Confirm order",
    description: "unrecognized reply at summary re-prompts",
    setup: [
      "ek zinger burger krdo",
      "bas yahi order h",
      "confirm krdo",
      "pickup chahiye",
      "Omar",
    ],
    message: "maybe later",
    intent: "re-prompt for YES/Cancel",
    expect: { cartChanges: false, phaseAfter: "checkout_summary", contains: ["YES"] },
  },
  {
    id: "cf-009",
    category: "Confirm order",
    description: "bilkul theek hai phrasing during review",
    setup: ["ek zinger burger krdo", "bas yahi order h"],
    message: "bilkul theek hai",
    intent: "move to delivery/pickup selection",
    expect: { cartChanges: false, phaseAfter: "checkout_type", contains: ["Delivery"] },
  },
  {
    id: "cf-010",
    category: "Confirm order",
    description: "haan confirm phrasing during review",
    setup: ["ek zinger burger krdo", "bas yahi order h"],
    message: "haan confirm",
    intent: "move to delivery/pickup selection",
    expect: { cartChanges: false, phaseAfter: "checkout_type", contains: ["Delivery"] },
  },
  {
    id: "cf-011",
    category: "Confirm order",
    description: "all good phrasing during review",
    setup: ["ek zinger burger krdo", "bas yahi order h"],
    message: "all good",
    intent: "move to delivery/pickup selection",
    expect: { cartChanges: false, phaseAfter: "checkout_type", contains: ["Delivery"] },
  },
  {
    id: "cf-012",
    category: "Confirm order",
    description: "ji haan at summary places the order",
    setup: [
      "ek zinger burger krdo",
      "bas yahi order h",
      "confirm krdo",
      "pickup chahiye",
      "Hamza",
    ],
    message: "ji haan",
    intent: "place order",
    expect: { cartChanges: false, confirmed: true },
  },
  {
    id: "cf-013",
    category: "Confirm order",
    description: "nahi cancel at summary aborts",
    setup: [
      "ek zinger burger krdo",
      "bas yahi order h",
      "confirm krdo",
      "pickup chahiye",
      "Mariam",
    ],
    message: "nahi cancel kr do",
    intent: "abort order, clear cart",
    expect: { cartChanges: true, cartAfter: [], phaseAfter: "browsing" },
  },
  {
    id: "cf-014",
    category: "Confirm order",
    description: "order confirm karo phrasing during review",
    setup: ["ek zinger burger krdo", "bas yahi order h"],
    message: "order confirm karo",
    intent: "move to delivery/pickup selection",
    expect: { cartChanges: false, phaseAfter: "checkout_type", contains: ["Delivery"] },
  },
  {
    id: "cf-015",
    category: "Confirm order",
    description: "confirm krdo shorthand during review",
    setup: ["ek zinger burger krdo", "bas yahi order h"],
    message: "confirm krdo",
    intent: "move to delivery/pickup selection",
    expect: { cartChanges: false, phaseAfter: "checkout_type", contains: ["Delivery"] },
  },
];
