import type { TestCase } from "../types";

// Category 14 — cancelling / clearing the order before placement.
export const cancelOrderCases: TestCase[] = [
  {
    id: "ca-001",
    category: "Cancel order",
    description: "literal cancel order phrase",
    setup: ["ek zinger burger krdo"],
    message: "cancel order",
    intent: "clear cart",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "ca-002",
    category: "Cancel order",
    description: "cancel order with filler word",
    setup: ["ek zinger burger krdo"],
    message: "cancel my order",
    intent: "clear cart",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "ca-003",
    category: "Cancel order",
    description: "cancel the whole order, filler words",
    setup: ["ek zinger burger krdo", "ek pasta small bhi de do"],
    message: "cancel the whole order please",
    intent: "clear cart",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "ca-004",
    category: "Cancel order",
    description: "roman urdu sab hata do",
    setup: ["ek zinger burger krdo"],
    message: "sab hata do",
    intent: "clear cart",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "ca-005",
    category: "Cancel order",
    description: "remove everything literal",
    setup: ["ek zinger burger krdo", "ek pasta small bhi de do"],
    message: "remove everything",
    intent: "clear cart",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "ca-006",
    category: "Cancel order",
    description: "clear cart literal",
    setup: ["ek zinger burger krdo"],
    message: "clear cart",
    intent: "clear cart",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "ca-007",
    category: "Cancel order",
    description: "clear my cart with filler word",
    setup: ["ek zinger burger krdo"],
    message: "clear my cart please",
    intent: "clear cart",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "ca-008",
    category: "Cancel order",
    description: "cancel with empty cart is a no-op",
    message: "cancel order",
    intent: "no-op, nothing to cancel",
    expect: { cartChanges: false },
  },
  {
    id: "ca-009",
    category: "Cancel order",
    description: "cancel at checkout_summary aborts the whole flow",
    setup: [
      "ek zinger burger krdo",
      "bas yahi order h",
      "confirm krdo",
      "pickup chahiye",
      "Zara",
    ],
    message: "cancel",
    intent: "abort order entirely",
    expect: { cartChanges: true, cartAfter: [], phaseAfter: "browsing" },
  },
  {
    id: "ca-010",
    category: "Cancel order",
    description: "cancel and immediately reorder something else",
    setup: ["ek zinger burger krdo"],
    message: "sab cancel kar do, ek smoke burger de do",
    intent: "clear cart then add smoke burger",
    expect: { cartChanges: true, cartAfter: [{ name: "Smoke Burger", qty: 1 }], totalAfter: 550 },
  },
  {
    id: "ca-011",
    category: "Cancel order",
    description: "clear all literal phrase",
    setup: ["ek zinger burger krdo"],
    message: "clear all",
    intent: "clear cart",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "ca-012",
    category: "Cancel order",
    description: "delete everything with politeness",
    setup: ["ek zinger burger krdo", "ek pasta small bhi de do"],
    message: "delete everything please",
    intent: "clear cart",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "ca-013",
    category: "Cancel order",
    description: "poora order cancel with filler words",
    setup: ["ek zinger burger krdo"],
    message: "mera poora order cancel kr do",
    intent: "clear cart",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "ca-014",
    category: "Cancel order",
    description: "order-then-cancel word order (reversed phrasing)",
    setup: ["ek zinger burger krdo"],
    message: "is order ko cancel kr do",
    intent: "clear cart",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "ca-015",
    category: "Cancel order",
    description: "cart-then-cancel word order",
    setup: ["ek zinger burger krdo"],
    message: "puri cart cancel kr do",
    intent: "clear cart",
    expect: { cartChanges: true, cartAfter: [] },
  },
];
