import type { TestCase } from "../types";

// Category 15 — items that are not on the Think Food menu at all.
export const unavailableItemsCases: TestCase[] = [
  {
    id: "ua-001",
    category: "Unavailable items",
    description: "biryani request gets rice alternatives",
    message: "ek chicken biryani de do",
    intent: "off-menu, suggest rice alternatives",
    expect: { cartChanges: false, contains: ["Singaporean Rice"] },
  },
  {
    id: "ua-002",
    category: "Unavailable items",
    description: "karahi request gets grilled alternatives",
    message: "chicken karahi chahiye",
    intent: "off-menu, suggest grilled alternatives",
    expect: { cartChanges: false, contains: ["Chicken Steak"] },
  },
  {
    id: "ua-003",
    category: "Unavailable items",
    description: "shawarma request gets wrap/gyro alternatives",
    message: "shawarma hai kya",
    intent: "off-menu, suggest wrap/gyro",
    expect: { cartChanges: false, contains: ["Wrap"] },
  },
  {
    id: "ua-004",
    category: "Unavailable items",
    description: "cold drink request",
    message: "ek coke bhi de do",
    intent: "off-menu, drinks not available",
    expect: { cartChanges: false, contains: ["Drinks"] },
  },
  {
    id: "ua-005",
    category: "Unavailable items",
    description: "naan / roti request",
    message: "do roti bhi chahiye",
    intent: "off-menu, suggest bread alternatives",
    expect: { cartChanges: false, contains: ["Sandwiches"] },
  },
  {
    id: "ua-006",
    category: "Unavailable items",
    description: "broast request",
    message: "broast hai?",
    intent: "off-menu, suggest crispy chicken alternatives",
    expect: { cartChanges: false, contains: ["Chicken Strips"] },
  },
  {
    id: "ua-007",
    category: "Unavailable items",
    description: "tikka kabab request",
    message: "seekh kabab chahiye",
    intent: "off-menu, suggest grilled alternatives",
    expect: { cartChanges: false, contains: ["Chicken Steak"] },
  },
  {
    id: "ua-008",
    category: "Unavailable items",
    description: "daal sabzi request",
    message: "daal chawal de do",
    intent: "off-menu, suggest vegetable alternatives",
    expect: { cartChanges: false, contains: ["Vegetable"] },
  },
  {
    id: "ua-009",
    category: "Unavailable items",
    description: "completely unrelated off-menu word, no crash",
    message: "ek zinger burger aur ek samosa bhi de do",
    intent: "add zinger burger, flag samosa as unavailable",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 1 }], contains: ["Unavailable"] },
  },
  {
    id: "ua-010",
    category: "Unavailable items",
    description: "paratha matches the bread/roti alternative suggestion",
    message: "ek qeema paratha chahiye",
    intent: "off-menu, suggest bread alternatives",
    expect: { cartChanges: false, contains: ["Sandwiches"] },
  },
  {
    id: "ua-011",
    category: "Unavailable items",
    description: "haleem nihari request",
    message: "haleem chahiye",
    intent: "off-menu, suggest grilled alternatives",
    expect: { cartChanges: false, contains: ["Chicken Steak"] },
  },
  {
    id: "ua-012",
    category: "Unavailable items",
    description: "juice/lassi request",
    message: "mango lassi hai?",
    intent: "off-menu, drinks not available",
    expect: { cartChanges: false, contains: ["Drinks"] },
  },
];
