import type { TestCase } from "../types";

// Category 16 — customer copy-pastes a menu line (with bullet/PKR price) back at the bot.
export const copiedMenuPkrCases: TestCase[] = [
  {
    id: "cp-001",
    category: "Copied menu lines with PKR",
    description: "copied line with em-dash and PKR, add instruction appended",
    message: "Pizza Large 12 inch — PKR 1200 add kro",
    intent: "add pizza large from copied line",
    expect: { cartChanges: true, cartAfter: [{ name: "Pizza Large 12 inch", qty: 1 }], totalAfter: 1200 },
  },
  {
    id: "cp-002",
    category: "Copied menu lines with PKR",
    description: "copied line with bullet point",
    message: "• Zinger Burger — PKR 500 ye dedo",
    intent: "add zinger burger from copied line",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "cp-003",
    category: "Copied menu lines with PKR",
    description: "copied line with Rs. shorthand for price",
    message: "Chicken Steak Rs. 950 chahiye",
    intent: "add chicken steak from copied line",
    expect: { cartChanges: true, cartAfter: [{ name: "Chicken Steak", qty: 1 }], totalAfter: 950 },
  },
  {
    id: "cp-004",
    category: "Copied menu lines with PKR",
    description: "full copied line, no add verb at all",
    message: "Hot Shot 8 pcs with fries — PKR 800",
    intent: "add hot shot from exact copied menu line",
    expect: { cartChanges: true, cartAfter: [{ name: "Hot Shot 8 pcs with fries", qty: 1 }], totalAfter: 800 },
  },
  {
    id: "cp-005",
    category: "Copied menu lines with PKR",
    description: "copied line with rupees spelled out",
    message: "Singaporean Rice rupees 700 mangwa do",
    intent: "add singaporean rice from copied line",
    expect: { cartChanges: true, cartAfter: [{ name: "Singaporean Rice", qty: 1 }], totalAfter: 700 },
  },
  {
    id: "cp-006",
    category: "Copied menu lines with PKR",
    description: "two copied lines pasted together",
    message: "Zinger Burger — PKR 500\nPasta Small — PKR 500 add kar do",
    intent: "add zinger burger + pasta small from copied lines",
    expect: {
      cartChanges: true,
      cartAfter: [
        { name: "Zinger Burger", qty: 1 },
        { name: "Pasta Small", qty: 1 },
      ],
      totalAfter: 1000,
    },
  },
  {
    id: "cp-007",
    category: "Copied menu lines with PKR",
    description: "copied line with arrow bullet style",
    message: "→ Grill Sandwich — PKR 650 chahiye",
    intent: "add grill sandwich from copied line",
    expect: { cartChanges: true, cartAfter: [{ name: "Grill Sandwich", qty: 1 }], totalAfter: 650 },
  },
  {
    id: "cp-008",
    category: "Copied menu lines with PKR",
    description: "copied price with comma-formatted thousands",
    message: "Think Food Special Pizza — PKR 1,500 chahiye",
    intent: "add special pizza from copied line",
    expect: { cartChanges: true, cartAfter: [{ name: "Think Food Special Pizza", qty: 1 }] },
  },
  {
    id: "cp-009",
    category: "Copied menu lines with PKR",
    description: "copied burger line",
    message: "Smoke Burger — PKR 550 chahiye",
    intent: "add smoke burger from copied line",
    expect: { cartChanges: true, cartAfter: [{ name: "Smoke Burger", qty: 1 }], totalAfter: 550 },
  },
  {
    id: "cp-010",
    category: "Copied menu lines with PKR",
    description: "copied sandwich line with add instruction",
    message: "Vegi Sandwich — PKR 500 add kar do",
    intent: "add vegi sandwich from copied line",
    expect: { cartChanges: true, cartAfter: [{ name: "Vegi Sandwich", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "cp-011",
    category: "Copied menu lines with PKR",
    description: "copied starter line",
    message: "Chicken Strips 6 pcs with fries — PKR 750 chahiye",
    intent: "add chicken strips from copied line",
    expect: { cartChanges: true, cartAfter: [{ name: "Chicken Strips 6 pcs with fries", qty: 1 }], totalAfter: 750 },
  },
  {
    id: "cp-012",
    category: "Copied menu lines with PKR",
    description: "copied roll line",
    message: "Wrap — PKR 550 de do",
    intent: "add wrap from copied line",
    expect: { cartChanges: true, cartAfter: [{ name: "Wrap", qty: 1 }], totalAfter: 550 },
  },
  {
    id: "cp-013",
    category: "Copied menu lines with PKR",
    description: "copied line with Rs shorthand, no period",
    message: "Mexican Sandwich Rs 600 chahiye",
    intent: "add mexican sandwich from copied line",
    expect: { cartChanges: true, cartAfter: [{ name: "Mexican Sandwich", qty: 1 }], totalAfter: 600 },
  },
  {
    id: "cp-014",
    category: "Copied menu lines with PKR",
    description: "copied pasta line with explicit qty word",
    message: "Pasta Large — PKR 600 ek de do",
    intent: "add pasta large from copied line",
    expect: { cartChanges: true, cartAfter: [{ name: "Pasta Large", qty: 1 }], totalAfter: 600 },
  },
  {
    id: "cp-015",
    category: "Copied menu lines with PKR",
    description: "copied rice line",
    message: "Egg Rice — PKR 450 add kr do",
    intent: "add egg rice from copied line",
    expect: { cartChanges: true, cartAfter: [{ name: "Egg Rice", qty: 1 }], totalAfter: 450 },
  },
];
