import type { TestCase } from "../types";

// Category 17 — confused customers (lost track of cart, unclear what they asked for).
export const customerConfusionCases: TestCase[] = [
  {
    id: "cc-001",
    category: "Customer confusion",
    description: "asks what they already ordered",
    setup: ["ek zinger burger krdo", "ek pasta small bhi de do"],
    message: "mene kya order kiya tha",
    intent: "show current order",
    expect: { cartChanges: false, contains: ["Zinger Burger"] },
  },
  {
    id: "cc-002",
    category: "Customer confusion",
    description: "explicit confusion statement, cart untouched",
    setup: ["ek zinger burger krdo"],
    message: "mujhe samajh nahi aya, mera order kya hai",
    intent: "show current order",
    expect: { cartChanges: false, contains: ["Zinger Burger"] },
  },
  {
    id: "cc-003",
    category: "Customer confusion",
    description: "asks to show order summary",
    setup: ["ek zinger burger krdo", "ek pasta small bhi de do"],
    message: "mera order dikhao",
    intent: "show current order",
    expect: { cartChanges: false, contains: ["Pasta Small"] },
  },
  {
    id: "cc-004",
    category: "Customer confusion",
    description: "asks if bot understood correctly",
    setup: ["ek zinger burger krdo"],
    message: "ye sahi samajhe ho na aap?",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "cc-005",
    category: "Customer confusion",
    description: "confused about price total",
    setup: ["ek zinger burger krdo", "ek pizza large bhi de do"],
    message: "ye total kaise bana, samajh nahi aya",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "cc-006",
    category: "Customer confusion",
    description: "customer contradicts themselves in one message",
    setup: ["ek zinger burger krdo"],
    message: "haan nahi wait confused hun",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "cc-007",
    category: "Customer confusion",
    description: "customer asks bot to repeat the order",
    setup: ["ek smoke burger chahiye"],
    message: "dobara batao kya order hai mera",
    intent: "show current order",
    expect: { cartChanges: false, contains: ["Smoke Burger"] },
  },
  {
    id: "cc-008",
    category: "Customer confusion",
    description: "empty-ish confused message with just a question mark",
    setup: ["ek zinger burger krdo"],
    message: "??",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "cc-009",
    category: "Customer confusion",
    description: "customer asks what just happened after an add",
    setup: ["ek zinger burger krdo"],
    message: "ye kya ho gaya abhi",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "cc-010",
    category: "Customer confusion",
    description: "customer unsure which item they meant",
    message: "wo wala jo pichli baar tha",
    intent: "no crash, graceful fallback, no menu context",
    expect: { cartChanges: false },
  },
  {
    id: "cc-011",
    category: "Customer confusion",
    description: "confused about who placed the order — incidental 'order' word, cart untouched",
    setup: ["ek zinger burger krdo"],
    message: "yeh order kisne diya tha",
    intent: "no crash, graceful fallback (known limitation: reads as a failed item match instead of showing cart)",
    expect: { cartChanges: false },
  },
  {
    id: "cc-012",
    category: "Customer confusion",
    description: "confused, can't remember the price",
    setup: ["ek pizza large bhi de do"],
    message: "ye kitna ka tha mujhe yaad nahi",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "cc-013",
    category: "Customer confusion",
    description: "second-guessing whether they already ordered",
    setup: ["ek zinger burger krdo"],
    message: "wait kya maine zinger order kiya tha ya nahi",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false, contains: ["Zinger Burger"] },
  },
  {
    id: "cc-014",
    category: "Customer confusion",
    description: "asks bot to repeat itself, no cart",
    message: "sorry kya bola aapne",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "cc-015",
    category: "Customer confusion",
    description: "general confusion about the whole conversation",
    setup: ["ek pasta small bhi de do"],
    message: "yeh sab kya hai samajh nahi raha",
    intent: "no crash, graceful fallback, cart preserved",
    expect: { cartChanges: false, contains: ["Pasta Small"] },
  },
];
