import type { TestCase } from "../types";

// Category 18 — frustrated / angry customers. Bot must stay helpful, never crash.
export const angryCustomerCases: TestCase[] = [
  {
    id: "an-001",
    category: "Angry customer",
    description: "frustration about delay, no item mentioned",
    setup: ["ek zinger burger krdo"],
    message: "itni dair kyun lag rahi hai yaar",
    intent: "no crash, cart untouched",
    expect: { cartChanges: false },
  },
  {
    id: "an-002",
    category: "Angry customer",
    description: "wants to talk to a human",
    message: "mujhe manager se baat karni hai abhi",
    intent: "escalate to human / manager",
    expect: { cartChanges: false, contains: ["naam"] },
  },
  {
    id: "an-003",
    category: "Angry customer",
    description: "complaint about wrong order in caps",
    setup: ["ek zinger burger krdo"],
    message: "YEH GALAT HAI MENE YE ORDER NAHI KIYA",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "an-004",
    category: "Angry customer",
    description: "angry but still wants to cancel cleanly",
    setup: ["ek zinger burger krdo", "ek pizza large bhi de do"],
    message: "bas cancel karo sab kuch, bohat bakwas service hai",
    intent: "clear cart despite angry tone",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "an-005",
    category: "Angry customer",
    description: "complaint with explicit complain keyword",
    message: "I want to complain about last order",
    intent: "escalate to human",
    expect: { cartChanges: false, contains: ["naam"] },
  },
  {
    id: "an-006",
    category: "Angry customer",
    description: "angry but reorders correctly mid-rant",
    message: "service bohat slow hai but theek hai, ek zinger burger de do",
    intent: "add zinger burger despite complaint prefix",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "an-007",
    category: "Angry customer",
    description: "angry punctuation spam, no crash",
    setup: ["ek zinger burger krdo"],
    message: "!!!!! kab milega order !!!!!",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "an-008",
    category: "Angry customer",
    description: "threatens to cancel and leave, still just cancels cart",
    setup: ["ek zinger burger krdo"],
    message: "bas mujhe ab order nahi karna, cancel everything",
    intent: "clear cart",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "an-009",
    category: "Angry customer",
    description: "supervisor escalation request",
    message: "supervisor se connect karwao",
    intent: "escalate to human",
    expect: { cartChanges: false, contains: ["naam"] },
  },
  {
    id: "an-010",
    category: "Angry customer",
    description: "sarcastic message, no menu words, no crash",
    message: "wah kya zabardast service hai really",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "an-011",
    category: "Angry customer",
    description: "complaint phrased as an order-status question",
    setup: ["ek zinger burger krdo"],
    message: "yeh kya bakwas hai, mera order kahan hai",
    intent: "show current order",
    expect: { cartChanges: false, contains: ["Zinger Burger"] },
  },
  {
    id: "an-012",
    category: "Angry customer",
    description: "complaint about prices, still places a real order",
    message: "itni mehngi cheezein hain phir bhi order krna hai ek zinger burger",
    intent: "add zinger burger despite complaint prefix",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "an-013",
    category: "Angry customer",
    description: "frustration leads to cancelling, reversed word order",
    setup: ["ek zinger burger krdo"],
    message: "service itni kharab hai ke bas ab order cancel hi karna behtar hai",
    intent: "clear cart",
    expect: { cartChanges: true, cartAfter: [] },
  },
  {
    id: "an-014",
    category: "Angry customer",
    description: "complaint about delay with empty cart, no crash",
    message: "kitni dair lagegi mera order abhi tak nahi aaya",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "an-015",
    category: "Angry customer",
    description: "impatient customer still places a clear order",
    message: "aap log time waste kar rahe ho, jaldi ek pizza large bhej do",
    intent: "add pizza large despite impatience",
    expect: { cartChanges: true, cartAfter: [{ name: "Pizza Large 12 inch", qty: 1 }], totalAfter: 1200 },
  },
];
