import type { TestCase } from "../types";

// Red team — completely off-topic questions a bored/distracted real customer
// sends mid-chat. Must never crash, never hallucinate a menu match, and must
// never corrupt an existing cart.
export const offTopicCases: TestCase[] = [
  {
    id: "ot-001",
    category: "Red team: off-topic",
    description: "cricket score question",
    setup: ["ek zinger burger krdo"],
    message: "aaj pakistan ka score kya hai",
    intent: "no crash, cart untouched",
    expect: { cartChanges: false, contains: ["Zinger Burger"] },
  },
  {
    id: "ot-002",
    category: "Red team: off-topic",
    description: "weather question",
    message: "aaj mausam kaisa hai karachi mein",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "ot-003",
    category: "Red team: off-topic",
    description: "asks for a joke",
    message: "koi joke sunao",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "ot-004",
    category: "Red team: off-topic",
    description: "asks about politics",
    message: "election kab hain is saal",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "ot-005",
    category: "Red team: off-topic",
    description: "asks bot if it's a real human",
    message: "tum insaan ho ya robot",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "ot-006",
    category: "Red team: off-topic",
    description: "random movie question with cart active",
    setup: ["ek pizza large bhi de do"],
    message: "koi achi movie suggest karo",
    intent: "no crash, cart untouched (note: 'suggest' is read as a food-recommendation request, a defensible food-focused fallback)",
    expect: { cartChanges: false },
  },
  {
    id: "ot-007",
    category: "Red team: off-topic",
    description: "asks bot's age",
    message: "aap ki age kitni hai",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "ot-008",
    category: "Red team: off-topic",
    description: "stock market question",
    message: "psx index kya chal raha hai aaj",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "ot-009",
    category: "Red team: off-topic",
    description: "asks for relationship advice",
    message: "meri girlfriend mujhse naraz hai kya karoon",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "ot-010",
    category: "Red team: off-topic",
    description: "random number trivia question",
    message: "duniya ki sabse lambi nadi konsi hai",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "ot-011",
    category: "Red team: off-topic",
    description: "asks bot to do math unrelated to order",
    message: "25 plus 37 kitna hota hai",
    intent: "no crash, no accidental cart mutation",
    expect: { cartChanges: false },
  },
  {
    id: "ot-012",
    category: "Red team: off-topic",
    description: "off-topic question phrased in english",
    message: "what's the capital of france",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "ot-013",
    category: "Red team: off-topic",
    description: "asks about a different restaurant entirely",
    message: "kfc ka number hai aapke paas",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "ot-014",
    category: "Red team: off-topic",
    description: "traffic update question",
    message: "shahrah-e-faisal pe traffic kaisa hai abhi",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "ot-015",
    category: "Red team: off-topic",
    description: "asks for a song recommendation with active cart",
    setup: ["ek smoke burger chahiye"],
    message: "koi acha gana batao",
    intent: "no crash, cart untouched",
    expect: { cartChanges: false, contains: ["Smoke Burger"] },
  },
  {
    id: "ot-016",
    category: "Red team: off-topic",
    description: "random number sent alone, no context",
    message: "786",
    intent: "no crash, no spurious add",
    expect: { cartChanges: false },
  },
  {
    id: "ot-017",
    category: "Red team: off-topic",
    description: "asks if bot can call them on phone",
    message: "mujhe call kar sakte ho",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "ot-018",
    category: "Red team: off-topic",
    description: "asks unrelated yes/no general knowledge question",
    message: "kya mangal grah par zindagi hai",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "ot-019",
    category: "Red team: off-topic",
    description: "tests bot with a riddle",
    message: "ek paheli batao zara",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "ot-020",
    category: "Red team: off-topic",
    description: "off-topic question containing a menu word coincidentally",
    message: "mera dost steak house mein kaam karta hai",
    intent: "off-topic mention of 'steak' should not silently add it",
    expect: { cartChanges: false },
  },
];
