import type { TestCase } from "../types";

// Red team — emoji-only messages and "voice-typing style" input (no
// punctuation, run-on phonetic spelling, the way phone dictation transcribes).
export const emojiVoiceCases: TestCase[] = [
  {
    id: "ev-001",
    category: "Red team: emoji / voice-typing",
    description: "single thumbs up emoji, no cart",
    message: "👍",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "ev-002",
    category: "Red team: emoji / voice-typing",
    description: "thumbs up after checkout review treated as non-confirm",
    setup: ["ek zinger burger krdo", "bas yahi order h"],
    message: "👍",
    intent: "not recognized as explicit confirm, cart/phase untouched",
    expect: { cartChanges: false, phaseAfter: "checkout_review" },
  },
  {
    id: "ev-003",
    category: "Red team: emoji / voice-typing",
    description: "pizza emoji only, no text",
    message: "🍕",
    intent: "no crash, no spurious add (emoji alone isn't a menu word)",
    expect: { cartChanges: false },
  },
  {
    id: "ev-004",
    category: "Red team: emoji / voice-typing",
    description: "burger emoji with item word still resolves via the word",
    message: "🍔 zinger burger chahiye",
    intent: "add zinger burger despite leading emoji",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "ev-005",
    category: "Red team: emoji / voice-typing",
    description: "angry face emoji with cart active",
    setup: ["ek zinger burger krdo"],
    message: "😡😡😡",
    intent: "no crash, cart untouched",
    expect: { cartChanges: false },
  },
  {
    id: "ev-006",
    category: "Red team: emoji / voice-typing",
    description: "fire emoji spam",
    message: "🔥🔥🔥🔥🔥",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "ev-007",
    category: "Red team: emoji / voice-typing",
    description: "voice-typing run-on, no punctuation, no capitalization",
    message: "haan bhai mujhe ek zinger burger aur ek pasta small chahiye jaldi bhej dena",
    intent: "add zinger burger + pasta small",
    expect: {
      cartChanges: true,
      cartAfter: [
        { name: "Zinger Burger", qty: 1 },
        { name: "Pasta Small", qty: 1 },
      ],
      totalAfter: 1000,
    },
  },
  {
    id: "ev-008",
    category: "Red team: emoji / voice-typing",
    description: "voice-typing phonetic mishear of 'chahiye' as 'chaiyeh'",
    message: "ek hot shot chaiyeh",
    intent: "add hot shot",
    expect: { cartChanges: true, cartAfter: [{ name: "Hot Shot 8 pcs with fries", qty: 1 }], totalAfter: 800 },
  },
  {
    id: "ev-009",
    category: "Red team: emoji / voice-typing",
    description: "voice-typing dropped the comma, items run together",
    message: "ek zinger burger ek pasta small chahiye",
    intent: "add zinger burger + pasta small via sub-split on repeated qty word",
    expect: {
      cartChanges: true,
      cartAfter: [
        { name: "Zinger Burger", qty: 1 },
        { name: "Pasta Small", qty: 1 },
      ],
      totalAfter: 1000,
    },
  },
  {
    id: "ev-010",
    category: "Red team: emoji / voice-typing",
    description: "check mark emoji as a confirm attempt during review",
    setup: ["ek zinger burger krdo", "bas yahi order h"],
    message: "✅ confirm",
    intent: "confirm despite leading emoji",
    expect: { cartChanges: false, phaseAfter: "checkout_type", contains: ["Delivery"] },
  },
  {
    id: "ev-011",
    category: "Red team: emoji / voice-typing",
    description: "crying emoji complaint, cart untouched",
    setup: ["ek zinger burger krdo"],
    message: "😭😭 itni dair kyun lag rahi",
    intent: "no crash, cart untouched",
    expect: { cartChanges: false },
  },
  {
    id: "ev-012",
    category: "Red team: emoji / voice-typing",
    description: "heart emoji thank you message",
    message: "thank you ❤️",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "ev-013",
    category: "Red team: emoji / voice-typing",
    description: "voice-typing long run-on sentence with no stops at all",
    message: "haan ji bilkul theek hai mujhe ek mexican pizza chahiye aur saath mein ek hot shot bhi de dena please",
    intent: "add mexican pizza + hot shot",
    expect: {
      cartChanges: true,
      cartAfter: [
        { name: "Mexican Pizza", qty: 1 },
        { name: "Hot Shot 8 pcs with fries", qty: 1 },
      ],
      totalAfter: 2400,
    },
  },
  {
    id: "ev-014",
    category: "Red team: emoji / voice-typing",
    description: "laughing emoji combined with a real order",
    message: "lol 😂 ek smoke burger de do",
    intent: "add smoke burger despite emoji/laughter prefix",
    expect: { cartChanges: true, cartAfter: [{ name: "Smoke Burger", qty: 1 }], totalAfter: 550 },
  },
  {
    id: "ev-015",
    category: "Red team: emoji / voice-typing",
    description: "100 emoji used as emphasis, no real quantity meaning",
    setup: ["ek zinger burger krdo"],
    message: "ye order perfect hai 💯",
    intent: "no crash, cart untouched (known limitation: incidental 'order' word reads as a failed item match instead of showing the cart)",
    expect: { cartChanges: false },
  },
];
