import type { TestCase } from "../types";

// Red team — customers who change their mind, contradict themselves, or
// interrupt their own sentence mid-order.
export const contradictionCases: TestCase[] = [
  {
    id: "rt-001",
    category: "Red team: contradictions / changes mind",
    description: "orders then immediately says no then re-confirms via new item",
    message: "ek zinger burger... nahi nahi ek smoke burger de do",
    intent: "final stated intent (smoke burger) wins",
    expect: { cartChanges: true, cartAfter: [{ name: "Smoke Burger", qty: 1 }], totalAfter: 550 },
  },
  {
    id: "rt-002",
    category: "Red team: contradictions / changes mind",
    description: "asks for delivery then immediately switches to pickup",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "delivery"],
    message: "pickup",
    intent: "switch from delivery to pickup mid checkout_address",
    expect: { cartChanges: false, phaseAfter: "checkout_name", contains: ["naam"] },
  },
  {
    id: "rt-003",
    category: "Red team: contradictions / changes mind",
    description: "says small then immediately corrects to large — genuinely ambiguous, bot asks rather than guesses",
    message: "ek pizza small... actually large kar do",
    intent: "no crash; ambiguous self-correction with no cart context yet, so a clarifying question is the safe choice",
    expect: { cartChanges: false, contains: ["Pizza Large 12 inch"] },
  },
  {
    id: "rt-004",
    category: "Red team: contradictions / changes mind",
    description: "adds two of an item then says they only want one",
    setup: ["2 zinger burger"],
    message: "1 zinger burger kar do",
    intent: "correct quantity down to 1",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "rt-005",
    category: "Red team: contradictions / changes mind",
    description: "cancels then immediately reorders the exact same thing",
    setup: ["ek zinger burger krdo"],
    message: "cancel order, ek zinger burger phir se de do",
    intent: "clear then re-add zinger burger",
    expect: { cartChanges: false, cartAfter: [{ name: "Zinger Burger", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "rt-006",
    category: "Red team: contradictions / changes mind",
    description: "says yes then no in the same breath at checkout summary",
    setup: [
      "ek zinger burger krdo",
      "bas yahi order h",
      "confirm krdo",
      "pickup chahiye",
      "Ahmed",
    ],
    message: "haan... nahi wait cancel",
    intent: "no crash; explicit cancel word should win",
    expect: { cartChanges: true, cartAfter: [], phaseAfter: "browsing" },
  },
  {
    id: "rt-007",
    category: "Red team: contradictions / changes mind",
    description: "asks for an item then says never mind, keeps cart as-is",
    setup: ["ek zinger burger krdo"],
    message: "ek pizza large bhi... actually rehne do",
    intent: "no crash, reasonable outcome",
    expect: { cartChanges: false },
  },
  {
    id: "rt-008",
    category: "Red team: contradictions / changes mind",
    description: "swaps item twice in a row, second swap should win",
    setup: ["ek zinger burger lena hai"],
    message: "zinger nahi smoke burger kar do",
    intent: "first swap: zinger to smoke burger",
    expect: { cartChanges: true, cartAfter: [{ name: "Smoke Burger", qty: 1 }], totalAfter: 550 },
  },
  {
    id: "rt-009",
    category: "Red team: contradictions / changes mind",
    description: "second swap on top of the first swap",
    setup: ["ek zinger burger lena hai", "zinger nahi smoke burger kar do"],
    message: "smoke nahi spicy stuff burger kar do",
    intent: "second swap: smoke burger to spicy stuff burger",
    expect: { cartChanges: true, cartAfter: [{ name: "Spicy Stuff Burger", qty: 1 }], totalAfter: 700 },
  },
  {
    id: "rt-010",
    category: "Red team: contradictions / changes mind",
    description: "explicitly says 'I changed my mind' then orders something new",
    setup: ["ek pizza large bhi de do"],
    message: "maine mind change kar liya, ab mujhe ek pasta large chahiye",
    intent: "no crash, adds pasta large alongside or in place of existing item",
    expect: { cartChanges: true },
  },
  {
    id: "rt-011",
    category: "Red team: contradictions / changes mind",
    description: "asks to remove an item then immediately re-adds the same one",
    setup: ["ek zinger burger krdo"],
    message: "zinger hata do, phir se ek zinger burger de do",
    intent: "remove then re-add zinger burger — net result still 1 in cart",
    expect: { cartChanges: false, cartAfter: [{ name: "Zinger Burger", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "rt-012",
    category: "Red team: contradictions / changes mind",
    description: "claims they never ordered anything despite a populated cart",
    setup: ["ek zinger burger krdo"],
    message: "maine kuch order nahi kiya tha",
    intent: "no crash, cart stays as the source of truth",
    expect: { cartChanges: false },
  },
];
