import type { TestCase } from "../types";

// Red team — customer interrupts their own checkout flow with unrelated
// requests, item edits, or questions partway through delivery/pickup/name.
export const interruptsCheckoutCases: TestCase[] = [
  {
    id: "ic-001",
    category: "Red team: interrupts checkout",
    description: "asks delivery time mid checkout_type instead of answering",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo"],
    message: "delivery mein kitna time lagega",
    intent: "answers delivery time, does not advance checkout phase incorrectly",
    expect: { cartChanges: false, phaseAfter: "checkout_type" },
  },
  {
    id: "ic-002",
    category: "Red team: interrupts checkout",
    description: "tries to add another item while typing the address",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "delivery"],
    message: "ek pasta small bhi add kar do",
    intent: "no crash; address step keeps asking for a valid address",
    expect: { cartChanges: false, phaseAfter: "checkout_address" },
  },
  {
    id: "ic-003",
    category: "Red team: interrupts checkout",
    description: "asks an off-topic question while bot is waiting for their name",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "pickup chahiye"],
    message: "aap log kab tak khule rehte hain",
    intent: "no crash, name still required",
    expect: { cartChanges: false, phaseAfter: "checkout_name" },
  },
  {
    id: "ic-004",
    category: "Red team: interrupts checkout",
    description: "switches delivery type after already giving an address",
    setup: [
      "ek zinger burger krdo",
      "place order",
      "confirm krdo",
      "delivery",
      "House 12 Street 5 Gulshan Karachi",
    ],
    message: "pickup chahiye",
    intent: "no crash; name step already reached, pickup mention here doesn't break it",
    expect: { cartChanges: false, phaseAfter: "checkout_name" },
  },
  {
    id: "ic-005",
    category: "Red team: interrupts checkout",
    description: "gives name then immediately tries to add an item",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "pickup chahiye", "Bilal"],
    message: "ek pizza large bhi de do",
    intent: "no crash at checkout_summary, still asks for YES/Cancel",
    expect: { cartChanges: false, phaseAfter: "checkout_summary", contains: ["YES"] },
  },
  {
    id: "ic-006",
    category: "Red team: interrupts checkout",
    description: "asks for the total again right before confirming",
    setup: ["ek zinger burger krdo", "bas yahi order h"],
    message: "total kitna hai dobara batao",
    intent: "no crash, stays in checkout_review",
    expect: { cartChanges: false, phaseAfter: "checkout_review" },
  },
  {
    id: "ic-007",
    category: "Red team: interrupts checkout",
    description: "tries to remove an item mid checkout_review",
    setup: ["ek zinger burger krdo", "ek pasta small bhi de do", "bas yahi order h"],
    message: "pasta hata do",
    intent: "remove pasta even while in checkout_review",
    expect: { cartChanges: true, cartAfter: [{ name: "Zinger Burger", qty: 1 }], totalAfter: 500 },
  },
  {
    id: "ic-008",
    category: "Red team: interrupts checkout",
    description: "asks for restaurant address while giving their own delivery address",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "delivery"],
    message: "aap ka restaurant kahan hai",
    intent: "no crash; this isn't a valid customer address, still asks for one",
    expect: { cartChanges: false, phaseAfter: "checkout_address" },
  },
  {
    id: "ic-009",
    category: "Red team: interrupts checkout",
    description: "provides a valid address that also happens to mention a menu word",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "delivery"],
    message: "House 7 Burger Street Gulshan Karachi",
    intent: "address accepted despite containing the word burger",
    expect: { cartChanges: false, phaseAfter: "checkout_name", contains: ["naam"] },
  },
  {
    id: "ic-010",
    category: "Red team: interrupts checkout",
    description: "declines delivery/pickup choice — pauses checkout but keeps the cart, doesn't wipe it",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo"],
    message: "nahi cancel kar do sab kuch",
    intent: "exit checkout flow back to item_selected, cart preserved",
    expect: { cartChanges: false, phaseAfter: "item_selected" },
  },
];
