import type { TestCase } from "../types";

// Red team — restaurant info queries phrased many different ways, plus a
// final batch of miscellaneous adversarial one-offs that don't fit elsewhere.
export const infoStressCases: TestCase[] = [
  {
    id: "is-001",
    category: "Red team: info & misc stress",
    description: "address query, roman urdu",
    message: "aap ki shop kahan hai",
    intent: "location info",
    expect: { cartChanges: false, contains: ["Nazimabad"] },
  },
  {
    id: "is-002",
    category: "Red team: info & misc stress",
    description: "address query, english",
    message: "what is your address",
    intent: "location info",
    expect: { cartChanges: false, contains: ["Nazimabad"] },
  },
  {
    id: "is-003",
    category: "Red team: info & misc stress",
    description: "timing query, roman urdu",
    message: "aap kab khulte hain",
    intent: "timing info",
    expect: { cartChanges: false, contains: ["PM"] },
  },
  {
    id: "is-004",
    category: "Red team: info & misc stress",
    description: "phone number query",
    message: "aapka number kya hai",
    intent: "contact info",
    expect: { cartChanges: false, contains: ["0312"] },
  },
  {
    id: "is-005",
    category: "Red team: info & misc stress",
    description: "delivery fee query",
    message: "delivery ka charge kitna hai",
    intent: "delivery fee info",
    expect: { cartChanges: false, contains: ["150"] },
  },
  {
    id: "is-006",
    category: "Red team: info & misc stress",
    description: "delivery time query with active cart",
    setup: ["ek zinger burger krdo"],
    message: "delivery mein kitna time lagta hai",
    intent: "delivery time info, cart untouched",
    expect: { cartChanges: false, contains: ["45 minutes"] },
  },
  {
    id: "is-007",
    category: "Red team: info & misc stress",
    description: "maps link request",
    message: "google maps link bhej do",
    intent: "location info with maps link",
    expect: { cartChanges: false, contains: ["maps"] },
  },
  {
    id: "is-008",
    category: "Red team: info & misc stress",
    description: "asks for a deal/combo that doesn't exist",
    message: "koi deal ya combo offer hai kya",
    intent: "no deals available, suggest menu browsing",
    expect: { cartChanges: false, contains: ["deal"] },
  },
  {
    id: "is-009",
    category: "Red team: info & misc stress",
    description: "asks for a recommendation with empty cart",
    message: "kya recommend karte ho aap",
    intent: "top picks shown",
    expect: { cartChanges: false, contains: ["Think Food SP Burger"] },
  },
  {
    id: "is-010",
    category: "Red team: info & misc stress",
    description: "comparison between two specific items",
    message: "jumbo zinger ya zinger burger, konsa behtar hai",
    intent: "comparison response",
    expect: { cartChanges: false, contains: ["750"] },
  },
  {
    id: "is-011",
    category: "Red team: info & misc stress",
    description: "rice vs noodles category comparison",
    message: "rice ya noodles, kya better hai",
    intent: "category comparison response",
    expect: { cartChanges: false, contains: ["Rice"] },
  },
  {
    id: "is-012",
    category: "Red team: info & misc stress",
    description: "budget query for a group with no explicit numbers beyond person count",
    message: "5 logon ke liye kuch suggest karo",
    intent: "group recommendation without a budget figure",
    expect: { cartChanges: false, contains: ["5 logon"] },
  },
  {
    id: "is-013",
    category: "Red team: info & misc stress",
    description: "low budget query gets honest 'nothing fits' answer",
    message: "150 rupees mein kuch milega kya",
    intent: "honest low-budget response, no hallucinated cheap item",
    expect: { cartChanges: false, contains: ["nahi milega"] },
  },
  {
    id: "is-014",
    category: "Red team: info & misc stress",
    description: "high budget query gets premium suggestions",
    message: "1500 rupees mein kya best milega",
    intent: "premium recommendation",
    expect: { cartChanges: false, contains: ["Chicken Steak"] },
  },
  {
    id: "is-015",
    category: "Red team: info & misc stress",
    description: "human escalation request with polite phrasing",
    message: "kya mujhe kisi insaan se baat karni hai",
    intent: "escalate to human contact",
    expect: { cartChanges: false, contains: ["naam"] },
  },
  {
    id: "is-016",
    category: "Red team: info & misc stress",
    description: "full menu request, explicit phrase",
    message: "poora menu dikha do please",
    intent: "show full menu",
    expect: { cartChanges: false, contains: ["Burgers", "Pizza", "Pasta"] },
  },
  {
    id: "is-017",
    category: "Red team: info & misc stress",
    description: "menu request with active cart should not clear it",
    setup: ["ek zinger burger krdo"],
    message: "menu dikhao",
    intent: "show menu without touching the existing cart",
    expect: { cartChanges: false, contains: ["Burgers"] },
  },
  {
    id: "is-018",
    category: "Red team: info & misc stress",
    description: "extremely long off-topic rant with no menu words at all",
    message:
      "yaar aaj traffic itna zyada tha raste mein, phir petrol bhi khatam ho gaya, office bhi late pohncha, bohat bura din tha aaj mera",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "is-019",
    category: "Red team: info & misc stress",
    description: "reset-like request mid-order, not a real app command",
    setup: ["ek zinger burger krdo"],
    message: "sab kuch reset kar do",
    intent: "no crash; 'reset' isn't a recognized command, cart likely untouched",
    expect: { cartChanges: false },
  },
  {
    id: "is-020",
    category: "Red team: info & misc stress",
    description: "asks the bot to repeat the full menu in english",
    message: "show me the complete menu",
    intent: "show full menu",
    expect: { cartChanges: false, contains: ["Burgers"] },
  },
  {
    id: "is-021",
    category: "Red team: info & misc stress",
    description:
      "very long, fully grammatical English paragraph order — first two items resolve cleanly; " +
      "(known limitation) the third item's trailing '? Thank you so much.' noise isn't trimmed " +
      "(unlike leading noise), so it's dropped rather than silently added with the wrong qty",
    message:
      "Hello, I would like to place an order for delivery please. Could I get one Zinger Burger, one Pizza Large, and one Chicken Steak? Thank you so much.",
    intent: "add Zinger Burger + Pizza Large, move to checkout review",
    expect: {
      cartChanges: true,
      cartAfter: [
        { name: "Zinger Burger", qty: 1 },
        { name: "Pizza Large 12 inch", qty: 1 },
      ],
      totalAfter: 1700,
      phaseAfter: "checkout_review",
    },
  },
  {
    id: "is-022",
    category: "Red team: info & misc stress",
    description: "asks for the menu in the middle of checkout_address",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "delivery"],
    message: "menu dobara dikha do",
    intent: "no crash; still waiting for a valid address",
    expect: { cartChanges: false, phaseAfter: "checkout_address" },
  },
  {
    id: "is-023",
    category: "Red team: info & misc stress",
    description: "pickup time question with no cart at all",
    message: "pickup ke liye kitna wait karna padega",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "is-024",
    category: "Red team: info & misc stress",
    description: "asks whether the restaurant is open right now late at night",
    message: "abhi raat 2 baje khule ho aap log",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
  {
    id: "is-025",
    category: "Red team: info & misc stress",
    description: "single-character spam message",
    message: "aaaaaaaaaaaaaaaaaaaa",
    intent: "no crash, graceful fallback",
    expect: { cartChanges: false },
  },
];
