import type { TestCase } from "../types";

// ─── Step 7 — Full checkout flows, end to end ──────────────────────────────
// Cart -> Place Order -> Review -> Confirm -> Delivery-or-Pickup ->
// [address if delivery] -> name -> YES -> confirmed. Covers both delivery
// and pickup paths in full, plus name-extraction phrasing variants and
// address validation (accept/reject).
export const fullCheckoutFlowCases: TestCase[] = [
  {
    id: "fc-001",
    category: "Full checkout flows",
    description: "complete delivery flow end to end",
    setup: [
      "ek zinger burger krdo",
      "place order",
      "confirm krdo",
      "delivery",
      "House 45 Street 12 Nazimabad Karachi",
    ],
    message: "Ahmed",
    intent: "name accepted, summary shown with delivery fee and address",
    expect: {
      cartChanges: false,
      phaseAfter: "checkout_summary",
      contains: ["Ahmed", "Delivery Fee", "Nazimabad", "YES"],
    },
  },
  {
    id: "fc-002",
    category: "Full checkout flows",
    description: "complete delivery flow, then final YES confirms the order",
    setup: [
      "ek zinger burger krdo",
      "place order",
      "confirm krdo",
      "delivery",
      "House 45 Street 12 Nazimabad Karachi",
      "Ahmed",
    ],
    message: "YES",
    intent: "order placed",
    expect: { cartChanges: false, confirmed: true },
  },
  {
    id: "fc-003",
    category: "Full checkout flows",
    description: "complete pickup flow end to end — no address step, no delivery fee",
    setup: ["ek jumbo zinger krdo", "place order", "confirm krdo", "pickup"],
    message: "Sara",
    intent: "name accepted, pickup summary shown without delivery fee",
    expect: {
      cartChanges: false,
      phaseAfter: "checkout_summary",
      contains: ["Sara", "Pickup", "YES"],
      notContains: ["Delivery Fee"],
    },
  },
  {
    id: "fc-004",
    category: "Full checkout flows",
    description: "complete pickup flow, then final YES confirms the order",
    setup: ["ek jumbo zinger krdo", "place order", "confirm krdo", "pickup", "Sara"],
    message: "YES",
    intent: "order placed",
    expect: { cartChanges: false, confirmed: true },
  },
  {
    id: "fc-005",
    category: "Full checkout flows",
    description: "pickup type via 'pickup chahiye' phrasing",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo"],
    message: "pickup chahiye",
    intent: "pickup selected, asks for name",
    expect: { cartChanges: false, phaseAfter: "checkout_name", contains: ["naam"] },
  },
  {
    id: "fc-006",
    category: "Full checkout flows",
    description: "delivery type via 'delivery chahiye' phrasing",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo"],
    message: "delivery chahiye",
    intent: "delivery selected, asks for address",
    expect: { cartChanges: false, phaseAfter: "checkout_address", contains: ["address"] },
  },
  // ── Name extraction phrasing variants ──────────────────────────────────
  {
    id: "fc-007",
    category: "Full checkout flows",
    description: "name: plain single word",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "pickup"],
    message: "Bilal",
    intent: "name accepted as-is",
    expect: { cartChanges: false, phaseAfter: "checkout_summary", contains: ["Bilal"] },
  },
  {
    id: "fc-008",
    category: "Full checkout flows",
    description: "name: 'mera naam X hai'",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "pickup"],
    message: "mera naam Hassan hai",
    intent: "name extracted as Hassan",
    expect: { cartChanges: false, phaseAfter: "checkout_summary", contains: ["Hassan"] },
  },
  {
    id: "fc-009",
    category: "Full checkout flows",
    description: "name: 'my name is X'",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "pickup"],
    message: "my name is Fahad",
    intent: "name extracted as Fahad",
    expect: { cartChanges: false, phaseAfter: "checkout_summary", contains: ["Fahad"] },
  },
  {
    id: "fc-010",
    category: "Full checkout flows",
    description: "name: 'I am X'",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "pickup"],
    message: "I am Ayesha",
    intent: "name extracted as Ayesha",
    expect: { cartChanges: false, phaseAfter: "checkout_summary", contains: ["Ayesha"] },
  },
  {
    id: "fc-011",
    category: "Full checkout flows",
    description: "name: 'Main X hun'",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "pickup"],
    message: "main Hamza hun",
    intent: "name extracted as Hamza",
    expect: { cartChanges: false, phaseAfter: "checkout_summary", contains: ["Hamza"] },
  },
  {
    id: "fc-012",
    category: "Full checkout flows",
    description: "name: two-word full name",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "pickup"],
    message: "Ali Raza",
    intent: "full name accepted",
    expect: { cartChanges: false, phaseAfter: "checkout_summary", contains: ["Ali Raza"] },
  },
  {
    id: "fc-013",
    category: "Full checkout flows",
    description: "name rejected — contains a digit",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "pickup"],
    message: "Ali123",
    intent: "invalid name rejected, stays at checkout_name",
    expect: { cartChanges: false, phaseAfter: "checkout_name", contains: ["valid"] },
  },
  {
    id: "fc-014",
    category: "Full checkout flows",
    description: "name rejected — looks like a question",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "pickup"],
    message: "kyun puch rahe ho?",
    intent: "invalid name rejected, stays at checkout_name",
    expect: { cartChanges: false, phaseAfter: "checkout_name" },
  },
  {
    id: "fc-015",
    category: "Full checkout flows",
    description: "name rejected — too many words to be a real name",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "pickup"],
    message: "mera naam abhi yaad nahi araha hai dobara",
    intent: "invalid name rejected, stays at checkout_name",
    expect: { cartChanges: false, phaseAfter: "checkout_name" },
  },
  // ── Address validation ─────────────────────────────────────────────────
  {
    id: "fc-016",
    category: "Full checkout flows",
    description: "address accepted — has house/street number",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "delivery"],
    message: "House 12 Street 5 Gulshan Karachi",
    intent: "address accepted, moves to name",
    expect: { cartChanges: false, phaseAfter: "checkout_name", contains: ["naam"] },
  },
  {
    id: "fc-017",
    category: "Full checkout flows",
    description: "address accepted — recognisable area word, no digit",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "delivery"],
    message: "Near Clifton Block society Karachi",
    intent: "address accepted via address word even without a digit",
    expect: { cartChanges: false, phaseAfter: "checkout_name", contains: ["naam"] },
  },
  {
    id: "fc-018",
    category: "Full checkout flows",
    description: "address rejected — junk text",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "delivery"],
    message: "asdf",
    intent: "invalid address rejected, stays at checkout_address",
    expect: { cartChanges: false, phaseAfter: "checkout_address", contains: ["valid"] },
  },
  {
    id: "fc-019",
    category: "Full checkout flows",
    description: "address rejected — too short, no real content",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "delivery"],
    message: "ok",
    intent: "invalid address rejected, stays at checkout_address",
    expect: { cartChanges: false, phaseAfter: "checkout_address", contains: ["valid"] },
  },
  {
    id: "fc-020",
    category: "Full checkout flows",
    description: "address rejected — no digit, no address word, just chatter",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "delivery"],
    message: "mujhe nahi pata abhi",
    intent: "invalid address rejected, stays at checkout_address",
    expect: { cartChanges: false, phaseAfter: "checkout_address" },
  },
  {
    id: "fc-021",
    category: "Full checkout flows",
    description: "final summary cancelled with 'nahi cancel kar do' wipes the cart",
    setup: ["ek zinger burger krdo", "place order", "confirm krdo", "pickup", "Sara"],
    message: "nahi cancel kar do",
    intent: "order cancelled at final summary, cart cleared, back to browsing",
    expect: { cartChanges: true, cartAfter: [], phaseAfter: "browsing" },
  },
  {
    id: "fc-022",
    category: "Full checkout flows",
    description: "multi-item delivery flow keeps every item through to the final summary",
    setup: [
      "ek zinger burger, ek pasta small aur ek wrap chahiye",
      "place order",
      "confirm krdo",
      "delivery",
      "House 9 Street 3 DHA Karachi",
    ],
    message: "Usman",
    intent: "all 3 items survive the full checkout flow to the summary",
    expect: {
      cartChanges: false,
      phaseAfter: "checkout_summary",
      contains: ["Zinger Burger", "Pasta Small", "Wrap", "Usman"],
    },
  },
];
